ADVANCED_LESSON_CONTENT = {
    "cosmetology-hair-scalp": {
        "summary": "Connect hair-and-scalp science, visible assessment, cosmetic pH concepts, conditioning selection, and damage prevention to safe cosmetology service decisions.",
        "scope": "Cosmetic education only. Learners observe visible hair/scalp characteristics and select cosmetic care within lawful cosmetology scope; they do not diagnose or treat disease.",
        "estimated_minutes": 120,
        "prerequisites": ["Cosmetology Foundations"],
        "materials": ["Mannequin or consenting model", "Clean comb and sectioning clips", "Good task lighting", "Magnifying or approved scalp-viewing tool if available", "pH reference chart or cosmetic pH strips for instructor demonstration", "Sample shampoos and conditioners with manufacturer directions", "Consultation and observation worksheet"],
        "objectives": ["Identify basic hair shaft and scalp structures relevant to cosmetic services.", "Describe texture, density, porosity, elasticity, breakage, dryness, oiliness, flakes, and buildup using neutral language.", "Explain pH as a product characteristic without claiming that visual inspection alone measures scalp pH.", "Match general cosmetic cleansing and conditioning categories to visible hair needs and manufacturer directions.", "Recognize when a service should be modified, postponed, or referred."],
        "lesson_sections": [
            {"title": "Hair structure and condition", "content": "The visible hair shaft includes the cuticle and cortex, with a medulla present in some hair. Cosmetic service choices are influenced by texture, density, porosity, elasticity, prior chemical or heat exposure, and the amount and location of breakage. A learner should distinguish a cosmetic description such as dry-feeling, rough, brittle, tangled, or visibly broken hair from a medical diagnosis."},
            {"title": "Visible scalp observation", "content": "Under clean, consistent lighting, observe visible dryness, oiliness, flakes, product buildup, redness, abrasions, unusual lesions, or other changes. Ask the client about comfort, sensitivities, reactions, and recent services. Do not label a visible condition as eczema, psoriasis, fungal infection, alopecia, or another diagnosis. Concerning or unexplained findings should trigger postponement or referral rather than diagnosis."},
            {"title": "Dry scalp and product selection", "content": "Visible flaking or a dry-feeling scalp can have many causes, so cosmetic observation alone cannot determine the cause. Within cosmetic scope, a practitioner may avoid unnecessarily harsh cleansing, follow labeled directions for gentle cleansing or conditioning products, minimize irritating heat or friction, and monitor client comfort. Persistent, severe, painful, inflamed, bleeding, or otherwise concerning findings should be referred for appropriate healthcare evaluation."},
            {"title": "Damaged hair and conditioning", "content": "Hair that appears rough, porous, tangled, weak, or broken may benefit cosmetically from gentler handling and a conditioning strategy selected from manufacturer-labeled products. Rinse-out conditioners can improve manageability and slip; leave-in products may provide additional lubrication or protection; protein-containing or strengthening products may be appropriate when their labels and the hair condition support their use. More product is not automatically better. Avoid promising to permanently repair biological damage."},
            {"title": "Cosmetic pH education", "content": "pH describes how acidic or alkaline a water-based solution is. Product formulation and pH can influence how hair feels and behaves, particularly during chemical services. Learners should use manufacturer specifications or appropriate measurement methods when pH information is needed. A camera cannot reliably determine chemical pH from appearance alone. CrownPath AI must never invent a scalp-pH value from a photograph."},
            {"title": "Decision pathway", "content": "Proceed when the visible condition, history, product directions, and service plan are compatible. Modify the service when cosmetic dryness, fragility, porosity, or sensitivity calls for gentler technique. Postpone and refer when visible signs or reported symptoms suggest a concern outside cosmetic scope or when safe service requirements cannot be met."}
        ],
        "steps": ["Observe the hair and scalp under good lighting.", "Ask about prior services, sensitivities, and product reactions.", "Choose techniques based on condition and service goals.", "Refer suspected medical conditions rather than diagnosing them."],
        "demonstration": {"title": "Hair and scalp assessment demonstration", "instructions": ["Section the hair systematically and demonstrate consistent lighting.", "Describe only visible characteristics: density, texture, porosity clues, breakage, flakes, oiliness, dryness, redness, or buildup.", "Compare two manufacturer-labeled conditioning categories and explain why one may better fit the cosmetic goal.", "Demonstrate pH using a known liquid/product sample and an appropriate measurement method; explicitly show that a photograph does not provide a pH reading.", "Model referral language that avoids diagnosis."]},
        "guided_practice": ["Learners complete a neutral observation worksheet on a mannequin, model, or instructor-provided images.", "Learners choose a general cosmetic cleansing/conditioning approach and support the choice using visible characteristics and product directions.", "Learners practice explaining the limits of camera and AI assessment.", "Instructor presents referral scenarios and requires learners to state when they would stop or postpone service."],
        "knowledge_check": [
            {"question": "Can CrownPath determine a client's scalp pH from a photograph alone?", "options": ["Yes, exactly", "Yes, if the camera has high resolution", "No; appearance alone does not provide a reliable chemical pH measurement", "Only after a haircut"], "answer_index": 2, "rationale": "pH is a chemical property and should not be fabricated from visual appearance."},
            {"question": "Which description stays within cosmetic observation?", "options": ["You have psoriasis", "I can see visible flaking and redness, so I recommend postponing this service and seeking appropriate evaluation", "This conditioner will cure your scalp", "The camera confirms a fungal infection"], "answer_index": 1, "rationale": "The practitioner describes what is visible and makes a safe service decision without diagnosis."},
            {"question": "What is a reasonable goal of a conditioner for visibly dry or damaged hair?", "options": ["Permanently heal the hair", "Improve manageability, slip, feel, or protection according to the product directions", "Diagnose the cause of breakage", "Change scalp pH permanently"], "answer_index": 1, "rationale": "Conditioners provide cosmetic benefits; they do not diagnose or medically cure hair/scalp conditions."}
        ],
        "practical_checkoff": ["Uses consistent lighting and clean tools", "Describes visible hair/scalp characteristics neutrally", "Separates cosmetic observation from diagnosis", "Selects cosmetic products using label directions and service goals", "Explains pH limits accurately", "Recognizes referral and stop-service situations"],
        "avatar_bot": {"role": "Hair & Scalp Learning Guide", "allowed": ["Explain approved course concepts", "Prompt observation practice", "Compare approved cosmetic product categories", "Remind learners about referral boundaries"], "prohibited": ["Diagnose scalp disease", "Invent scalp pH from images", "Prescribe medication", "Promise cures", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Hair & Scalp Cosmetic Assessment", "sections": ["LOOK: density, texture, porosity clues, breakage, dryness, oiliness, flakes, buildup, redness.", "ASK: prior services, sensitivities, reactions, comfort, home-care products.", "SELECT: cosmetic cleansing/conditioning products from manufacturer directions and service goals.", "pH: use reliable product information or measurement; never guess a pH value from a photo.", "REFER: postpone when findings are concerning, unexplained, painful, inflamed, injured, or outside cosmetic scope."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "This lesson is educational and does not authorize medical diagnosis or treatment. Camera and AI tools may support documentation but must not diagnose disease or fabricate pH measurements."
    },
    "cosmetology-scalp-camera-assessment": {
        "summary": "Use standardized scalp photography and AI-assisted cosmetic observations to document visible changes while protecting consent, privacy, and professional scope.",
        "scope": "The camera and AI layer is a documentation and education aid. It may flag visible cosmetic patterns for human review but may not diagnose disease, prescribe treatment, or claim a chemical pH reading from an image.",
        "estimated_minutes": 90,
        "prerequisites": ["Cosmetology Foundations", "Hair & Scalp Science"],
        "materials": ["Approved camera or scalp imaging device", "Device cleaning supplies", "Consistent light source", "Consent form", "Secure client record", "Image comparison worksheet"],
        "objectives": ["Obtain informed permission before imaging.", "Capture repeatable scalp images.", "Document visible dryness, oiliness, flakes, buildup, breakage, density patterns, and redness neutrally.", "Use AI suggestions as review prompts rather than diagnoses.", "Protect image privacy and know when to refer."],
        "lesson_sections": [
            {"title": "Consent and privacy", "content": "Before taking a client image, explain why the image is being captured, where it will be stored, who may access it, and whether it will be used for teaching or comparison. Follow CrownPath privacy controls and applicable law. Do not use client images outside the approved purpose."},
            {"title": "Standardized image capture", "content": "Comparable images require repeatable lighting, distance, angle, magnification, parting pattern, and device cleanliness. Label images by date and approved scalp region rather than relying on memory. Poor image quality should be retaken rather than interpreted aggressively."},
            {"title": "AI-assisted cosmetic observations", "content": "CrownPath may be designed to highlight visible patterns such as apparent flakes, shine/oiliness, dryness, product buildup, breakage, or changes in visible density. These outputs should be phrased as observations or confidence-limited flags for a qualified human to review. The system must not convert a visual pattern into a medical diagnosis."},
            {"title": "Conditioning and care suggestions", "content": "When the visible observation remains within cosmetic scope, the system may support general product-category education such as gentle cleansing, rinse-out conditioning, leave-in conditioning, reduced heat, lower-friction handling, or protective styling. Product selection should remain tied to manufacturer directions, client history, practitioner judgment, and legal scope."},
            {"title": "Escalation", "content": "The practitioner should stop relying on cosmetic recommendations when images show or the client reports concerning pain, open injury, bleeding, severe inflammation, rapid unexplained change, or another issue outside scope. The appropriate action is referral, not automated diagnosis."}
        ],
        "steps": ["Explain the imaging process, privacy handling, and obtain permission.", "Capture comparable views using clean equipment and consistent lighting.", "Record objective visible observations and relevant client-reported history.", "Use the findings to select cosmetic conditioning, cleansing, protective-care, or referral options within scope."],
        "demonstration": {"title": "Standardized scalp-image session", "instructions": ["Show consent and privacy explanation.", "Clean the device and establish fixed lighting and distance.", "Capture the same scalp regions using a repeatable sequence.", "Review an example AI flag and restate it as a neutral observation requiring human review.", "Compare current and prior images without claiming diagnosis or pH measurement."]},
        "guided_practice": ["Learners capture a standardized image set on a mannequin or consenting model.", "Learners identify image-quality problems before interpreting the image.", "Learners write neutral cosmetic observations from sample images.", "Learners choose between proceed, modify, postpone/refer scenarios and explain why."],
        "knowledge_check": [
            {"question": "What should AI do when it detects a visual pattern that could have several causes?", "options": ["Name the disease", "Flag the visible pattern for human review and stay within cosmetic language", "Prescribe a treatment", "Automatically publish the client's image"], "answer_index": 1, "rationale": "AI should support observation and review, not diagnose."},
            {"question": "Why use consistent lighting and distance?", "options": ["To make images comparable over time", "To determine exact scalp pH", "To avoid obtaining consent", "To authorize medical treatment"], "answer_index": 0, "rationale": "Standardization improves useful visual comparison."}
        ],
        "practical_checkoff": ["Explains consent and privacy", "Cleans imaging equipment", "Uses consistent capture sequence", "Rejects poor-quality images", "Documents neutral observations", "Does not infer disease or pH", "Uses appropriate referral language"],
        "avatar_bot": {"role": "Scalp Camera Coach", "allowed": ["Guide image-capture sequence", "Check image-quality criteria", "Describe approved visible cosmetic categories", "Suggest approved educational product categories", "Prompt referral when configured safety boundaries are met"], "prohibited": ["Diagnose disease", "Generate medical treatment plans", "Claim exact pH from an image", "Override practitioner or Owner controls", "Expose client images without authorization"]},
        "student_handout": {"title": "Scalp Camera: Capture, Observe, Decide", "sections": ["CONSENT before capture.", "STANDARDIZE lighting, distance, angle, region, and device cleanliness.", "OBSERVE visible cosmetic characteristics only.", "AI FLAGS are prompts for human review, not diagnoses.", "pH cannot be reliably read from a photograph.", "PROCEED, MODIFY, or REFER based on scope, safety, history, and visible findings."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Imaging and AI assistance do not diagnose scalp disease, determine medical treatment, or replace licensed healthcare evaluation."
    },
    "barber-hair-scalp": {
        "summary": "Apply hair-and-scalp observation, texture and growth-pattern analysis, grooming product selection, conditioning concepts, and referral judgment to barber services.",
        "scope": "Barber education only. Learners may observe visible hair and scalp characteristics that affect grooming services, but they do not diagnose disease or provide medical treatment.",
        "estimated_minutes": 105,
        "prerequisites": ["Barber Foundations"],
        "materials": ["Mannequin or consenting model", "Clean barber combs and brushes", "Task lighting", "Approved scalp-viewing tool if available", "Sample shampoos, conditioners, scalp and grooming products with manufacturer directions", "Observation worksheet"],
        "objectives": ["Identify visible hair characteristics that affect cutting and grooming decisions.", "Describe visible dryness, oiliness, flakes, buildup, redness, breakage, density, texture, and growth direction neutrally.", "Use conditioning and grooming product categories according to label directions and client needs.", "Explain why appearance alone cannot provide an exact scalp pH measurement.", "Know when to modify, postpone, or refer a service."],
        "lesson_sections": [
            {"title": "Hair structure, texture, density, and growth", "content": "Barber service planning depends on texture, density, growth direction, cowlicks, whorls, hairline pattern, length, and the condition of the hair shaft. These characteristics affect guard selection, sectioning, fading, blending, edging, detangling, beard grooming, and styling. Observe before cutting so the service plan follows the client's actual growth pattern rather than a one-size-fits-all sequence."},
            {"title": "Visible scalp observation", "content": "Use good lighting to note visible dryness, flakes, shine or oiliness, buildup, redness, abrasions, irritation, or other changes. Ask about tenderness, recent reactions, and grooming products. State only what is visible. Do not identify a disease or promise treatment. When a finding appears concerning, unexplained, painful, inflamed, injured, or outside barber scope, postpone or modify the service and refer appropriately."},
            {"title": "Dryness, damaged hair, and conditioning", "content": "When hair appears rough, brittle, tangled, porous, or broken, use gentler combing and handling. A rinse-out conditioner may improve slip and manageability; a leave-in or grooming conditioner may add lubrication or protection when the label supports its use. For visible scalp dryness, avoid unnecessary friction and harsh cleansing. Product choice should follow manufacturer directions and client history rather than a diagnosis."},
            {"title": "Product selection for barbering", "content": "Pomades, creams, gels, oils, shampoos, conditioners, beard products, and scalp products differ in hold, finish, cleansing strength, weight, fragrance, and intended use. Match the product category to texture, desired finish, visible condition, sensitivities, and service goal. Patch or preliminary testing should be performed whenever required by product directions or applicable rules."},
            {"title": "Cosmetic pH boundaries", "content": "pH is a chemical characteristic of water-based solutions and can influence product performance. An image can show visible dryness or oiliness but cannot reliably reveal an exact scalp pH. CrownPath camera or AI features must not generate a made-up pH value from appearance. Use manufacturer information or an appropriate measurement method when pH data are actually needed."},
            {"title": "Cutting and grooming decision pathway", "content": "Proceed when the scalp and hair appear suitable for the planned barber service. Modify when fragility, dryness, sensitivity, or growth pattern calls for gentler technique or a different product. Postpone and refer when visible injury, severe inflammation, bleeding, unexplained rapid change, significant pain, or another concern falls outside barber scope."}
        ],
        "steps": ["Observe density, texture, growth direction, and visible scalp condition.", "Ask about sensitivities and prior reactions.", "Modify or postpone service when a visible condition raises safety concerns.", "Refer medical concerns to an appropriate licensed healthcare professional."],
        "demonstration": {"title": "Barber hair-and-scalp service planning", "instructions": ["Show a systematic observation of front, sides, crown, occipital area, hairline, and any relevant facial-hair area.", "Identify texture, density, growth direction, visible breakage, dryness, flakes, oiliness, buildup, and redness using neutral language.", "Explain how the observed growth pattern affects fade, taper, line-up, or grooming choices.", "Compare appropriate grooming or conditioning product categories using label directions.", "Model how to pause and refer without giving a diagnosis."]},
        "guided_practice": ["Learners complete a barber observation worksheet before choosing a cut or grooming plan.", "Learners select an appropriate general conditioning or styling category from instructor-approved product labels.", "Learners explain one modification for fragile or visibly dry hair.", "Learners practice referral wording for out-of-scope scalp concerns."],
        "knowledge_check": [
            {"question": "Which factor should be observed before establishing a fade or taper plan?", "options": ["Growth direction and density", "Only the client's shoe size", "A medical diagnosis from the camera", "An invented scalp pH"], "answer_index": 0, "rationale": "Growth direction and density directly affect barber cutting and blending decisions."},
            {"question": "What can CrownPath AI appropriately do with a clear scalp image?", "options": ["Diagnose psoriasis", "Flag visible flakes or redness for human review", "Prescribe medication", "Calculate exact scalp pH from appearance"], "answer_index": 1, "rationale": "AI may support cosmetic observation but must not diagnose or fabricate chemical measurements."},
            {"question": "What is an appropriate conditioner goal for visibly rough or damaged hair?", "options": ["Cure the biological damage", "Improve slip, manageability, feel, or protection according to product directions", "Treat a scalp disease", "Replace professional referral"], "answer_index": 1, "rationale": "Conditioning provides cosmetic benefits and should not be presented as medical treatment."}
        ],
        "practical_checkoff": ["Observes growth direction, texture, density, and visible condition before cutting", "Uses neutral cosmetic language", "Selects grooming or conditioning products from label directions", "Adjusts technique for fragility or dryness", "Does not diagnose or invent pH readings", "Uses safe referral language when appropriate"],
        "avatar_bot": {"role": "Barber Hair & Scalp Coach", "allowed": ["Prompt pre-cut observation", "Explain growth-pattern and product-selection concepts", "Coach neutral scalp descriptions", "Remind learners about stop-service and referral boundaries"], "prohibited": ["Diagnose scalp disease", "Invent scalp pH", "Prescribe treatment or medication", "Override state scope rules", "Reveal instructor answer keys"]},
        "student_handout": {"title": "Barber Hair & Scalp Decision Guide", "sections": ["OBSERVE: texture, density, growth direction, breakage, dryness, oiliness, flakes, buildup, redness.", "ASK: sensitivities, reactions, recent services, product use, discomfort.", "PLAN: guards, sections, blending zones, grooming and conditioning products according to service goal and labels.", "MODIFY: gentler handling for fragile or dry hair; reduce irritation and unnecessary friction.", "REFER: concerning pain, injury, bleeding, severe inflammation, unexplained rapid change, or another out-of-scope concern.", "AI/CAMERA: useful for documentation and comparison, not diagnosis or exact pH measurement."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Barbering education is not medical diagnosis or treatment. Current barber-board rules and manufacturer directions control where they are more specific."
    },
    "barber-scalp-camera-assessment": {
        "summary": "Use standardized scalp imaging to support barber consultation, haircut planning, grooming-product decisions, follow-up comparison, and safe referral without medical diagnosis.",
        "scope": "Camera and AI tools are documentation and education aids for visible cosmetic observations. They may not diagnose disease, prescribe treatment, or infer exact scalp pH from appearance.",
        "estimated_minutes": 90,
        "prerequisites": ["Barber Foundations", "Barber Hair & Scalp"],
        "materials": ["Approved scalp camera or imaging device", "Cleaning supplies for the device", "Consistent light source", "Client image-consent form", "Secure CrownPath client record", "Barber image-comparison worksheet"],
        "objectives": ["Obtain consent and explain image use.", "Capture repeatable scalp and hair images.", "Document visible cosmetic characteristics neutrally.", "Connect imaging observations to lawful barber service modifications and product categories.", "Use AI only as a human-reviewed aid and recognize referral triggers."],
        "lesson_sections": [
            {"title": "Permission and privacy", "content": "Before imaging, explain the purpose, storage, access, and intended use of the images. Obtain permission according to CrownPath policy and applicable law. Client images should never be repurposed for marketing, teaching, or public display without the required authorization."},
            {"title": "Barber imaging sequence", "content": "Use a repeatable sequence that can include hairline/front, right side, left side, crown, occipital area, and any service-relevant beard or facial-hair region when appropriate and consented to. Keep lighting, distance, angle, magnification, and parting pattern consistent so future images can be compared meaningfully."},
            {"title": "Approved visible categories", "content": "The image review may document apparent flakes, dryness, shine/oiliness, buildup, breakage, density pattern, growth direction, redness, or other visible cosmetic features. These should be recorded as observations, not disease labels. If the image is blurry or lighting is inconsistent, retake it rather than force an interpretation."},
            {"title": "AI-assisted barber planning", "content": "CrownPath AI may flag visible categories for a qualified human to review and may connect those observations to educational options such as gentler cleansing, conditioning, reduced friction, lower-tension styling, or altered grooming-product categories. It may also remind the barber to consider growth direction and fragile areas before cutting. The human barber remains responsible for the service decision."},
            {"title": "Referral and escalation", "content": "When the client reports significant pain or the image shows open injury, bleeding, severe inflammation, or another concerning change outside barber scope, stop cosmetic recommendation flow and refer appropriately. AI should never convert the image into a medical diagnosis or medical treatment recommendation."}
        ],
        "steps": ["Obtain client permission before capturing an image and explain how it will be used.", "Use consistent lighting, distance, and clean imaging equipment.", "Record only visible cosmetic observations such as flakes, dryness, oiliness, breakage, or product buildup.", "Choose an appropriate cosmetic care plan or pause and refer when signs fall outside barbering scope."],
        "demonstration": {"title": "Barber scalp-camera session", "instructions": ["Demonstrate consent and secure-record explanation.", "Clean the camera and establish a fixed capture sequence.", "Capture hairline, sides, crown, and occipital views using consistent technique.", "Review sample AI flags and translate them into neutral barber observations.", "Show how an observation may change grooming-product choice or cutting pressure without creating a diagnosis.", "Demonstrate a referral scenario where AI assistance stops and human escalation takes over."]},
        "guided_practice": ["Learners capture a standardized image set on a mannequin or consenting model.", "Learners reject and retake inconsistent or poor-quality images.", "Learners document neutral visible observations.", "Learners state one barber-service modification supported by the observation and product directions.", "Learners identify scenarios that require referral rather than a grooming recommendation."],
        "knowledge_check": [
            {"question": "Why should barber scalp images use the same angle, lighting, and distance each visit?", "options": ["To support meaningful comparison", "To diagnose disease", "To estimate exact scalp pH", "To eliminate consent"], "answer_index": 0, "rationale": "Standardized capture improves visual comparison over time."},
            {"question": "Which AI output is within CrownPath's intended barber scope?", "options": ["Fungal infection confirmed", "Visible flaking detected; review image and client history before making a cosmetic service decision", "Prescription required", "Scalp pH is exactly 5.2 from this photo"], "answer_index": 1, "rationale": "The system may flag a visible cosmetic pattern for human review without diagnosing or inventing a chemical measurement."},
            {"question": "What should happen when an image shows an open, bleeding area?", "options": ["Continue the haircut", "Cover it with styling product", "Pause the service and follow appropriate referral/safety procedures", "Ask AI to diagnose it"], "answer_index": 2, "rationale": "Open or bleeding areas require a safety response rather than routine cosmetic service."}
        ],
        "practical_checkoff": ["Obtains consent", "Cleans imaging device", "Uses standardized capture sequence", "Protects client image privacy", "Records neutral observations", "Connects observations to lawful barber decisions", "Does not diagnose or invent pH readings", "Recognizes and escalates referral scenarios"],
        "avatar_bot": {"role": "Barber Scalp Camera Coach", "allowed": ["Guide capture sequence", "Check image-quality criteria", "Prompt approved cosmetic observations", "Suggest instructor-approved grooming/conditioning categories", "Remind the learner to refer when configured red flags appear"], "prohibited": ["Diagnose disease", "Prescribe medical treatment", "Infer exact pH from images", "Publish client images without authorization", "Override barber, instructor, Owner, or security decisions"]},
        "student_handout": {"title": "Barber Camera Workflow: Consent → Capture → Observe → Decide", "sections": ["CONSENT: explain purpose, storage, and access.", "CAPTURE: same lighting, distance, angle, region, and device cleanliness.", "OBSERVE: flakes, dryness, oiliness, buildup, breakage, density pattern, growth direction, redness—neutral language only.", "DECIDE: proceed, modify grooming/cutting/product approach, or pause and refer.", "AI: may flag visible patterns for review; never diagnose or invent pH.", "PRIVACY: protect every client image as an authorized record."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Camera and AI observations are screening and documentation aids only. They must not diagnose disease or replace a qualified healthcare professional."
    },
}


def get_advanced_lesson_content(lesson_id: str):
    return ADVANCED_LESSON_CONTENT.get(lesson_id)
