ADVANCED_LESSON_CONTENT = {
    "cosmetology-hair-scalp": {
        "summary": "Connect hair-and-scalp science, visible assessment, cosmetic pH concepts, conditioning selection, and damage prevention to safe cosmetology service decisions.",
        "scope": "Cosmetic education only. Learners observe visible hair/scalp characteristics and select cosmetic care within lawful cosmetology scope; they do not diagnose or treat disease.",
        "estimated_minutes": 120,
        "prerequisites": ["Cosmetology Foundations"],
        "materials": ["Mannequin or consenting model", "Clean comb and sectioning clips", "Good task lighting", "Magnifying or approved scalp-viewing tool if available", "pH reference chart or cosmetic pH strips for instructor demonstration", "Sample shampoos and conditioners with manufacturer directions", "Consultation and observation worksheet"],
        "objectives": ["Identify basic hair shaft and scalp structures relevant to cosmetic services.", "Describe texture, density, porosity, elasticity, breakage, dryness, oiliness, flakes, and buildup using neutral language.", "Explain pH as a product characteristic without claiming that visual inspection alone measures scalp pH.", "Match general cosmetic cleansing and conditioning categories to visible hair needs and manufacturer directions.", "Recognize when a service should be modified, postponed, or referred."],
        "lesson_sections": [
            {"title": "Hair structure and condition", "content": "The visible hair shaft includes the cuticle and cortex, with a medulla present in some hair. Cosmetic service choices are influenced by texture, density, porosity, elasticity, prior chemical or heat exposure, and the amount and location of breakage. A learner should distinguish a cosmetic description such as dry-feeling, rough, brittle, tangled, or visibly broken hair from a medical diagnosis."},
            {"title": "Visible scalp observation", "content": "Under clean, consistent lighting, observe visible dryness, oiliness, flakes, product buildup, redness, abrasions, unusual lesions, or other changes. Ask the client about comfort, sensitivities, reactions, and recent services. Do not label a visible condition as eczema, psoriasis, fungal infection, alopecia, or another diagnosis. Concerning or unexplained findings should trigger postponement or referral rather than diagnosis."},
            {"title": "Dry scalp and product selection", "content": "Visible flaking or a dry-feeling scalp can have many causes, so cosmetic observation alone cannot determine the cause. Within cosmetic scope, a practitioner may avoid unnecessarily harsh cleansing, follow labeled directions for gentle cleansing or conditioning products, minimize irritating heat or friction, and monitor client comfort. Persistent, severe, painful, inflamed, bleeding, or otherwise concerning findings should be referred for appropriate healthcare evaluation."},
            {"title": "Damaged hair and conditioning", "content": "Hair that appears rough, porous, tangled, weak, or broken may benefit cosmetically from gentler handling and a conditioning strategy selected from manufacturer-labeled products. Rinse-out conditioners can improve manageability and slip; leave-in products may provide additional lubrication or protection; protein-containing or strengthening products may be appropriate when their labels and the hair condition support their use. More product is not automatically better. Avoid promising to permanently repair biological damage."},
            {"title": "Cosmetic pH education", "content": "pH describes how acidic or alkaline a water-based solution is. Product formulation and pH can influence how hair feels and behaves, particularly during chemical services. Learners should use manufacturer specifications or appropriate measurement methods when pH information is needed. A camera cannot reliably determine chemical pH from appearance alone. CrownPath AI must never invent a scalp-pH value from a photograph."},
            {"title": "Decision pathway", "content": "Proceed when the visible condition, history, product directions, and service plan are compatible. Modify the service when cosmetic dryness, fragility, porosity, or sensitivity calls for gentler technique. Postpone and refer when visible signs or reported symptoms suggest a concern outside cosmetic scope or when safe service requirements cannot be met."}
        ],
        "steps": ["Observe the hair and scalp under good lighting.", "Ask about prior services, sensitivities, and product reactions.", "Choose techniques based on condition and service goals.", "Refer suspected medical conditions rather than diagnosing them."],
        "demonstration": {"title": "Hair and scalp assessment demonstration", "instructions": ["Section the hair systematically and demonstrate consistent lighting.", "Describe only visible characteristics: density, texture, porosity clues, breakage, flakes, oiliness, dryness, redness, or buildup.", "Compare two manufacturer-labeled conditioning categories and explain why one may better fit the cosmetic goal.", "Demonstrate pH using a known liquid/product sample and an appropriate measurement method; explicitly show that a photograph does not provide a pH reading.", "Model referral language that avoids diagnosis."]},
        "guided_practice": ["Learners complete a neutral observation worksheet on a mannequin, model, or instructor-provided images.", "Learners choose a general cosmetic cleansing/conditioning approach and support the choice using visible characteristics and product directions.", "Learners practice explaining the limits of camera and AI assessment.", "Instructor presents referral scenarios and requires learners to state when they would stop or postpone service."],
        "knowledge_check": [
            {"question": "Can CrownPath determine a client's scalp pH from a photograph alone?", "options": ["Yes, exactly", "Yes, if the camera has high resolution", "No; appearance alone does not provide a reliable chemical pH measurement", "Only after a haircut"], "answer_index": 2, "rationale": "pH is a chemical property and should not be fabricated from visual appearance."},
            {"question": "Which description stays within cosmetic observation?", "options": ["You have psoriasis", "I can see visible flaking and redness, so I recommend postponing this service and seeking appropriate evaluation", "This conditioner will cure your scalp", "The camera confirms a fungal infection"], "answer_index": 1, "rationale": "The practitioner describes what is visible and makes a safe service decision without diagnosis."},
            {"question": "What is a reasonable goal of a conditioner for visibly dry or damaged hair?", "options": ["Permanently heal the hair", "Improve manageability, slip, feel, or protection according to the product directions", "Diagnose the cause of breakage", "Change scalp pH permanently"], "answer_index": 1, "rationale": "Conditioners provide cosmetic benefits; they do not diagnose or medically cure hair/scalp conditions."}
        ],
        "practical_checkoff": ["Uses consistent lighting and clean tools", "Describes visible hair/scalp characteristics neutrally", "Separates cosmetic observation from diagnosis", "Selects cosmetic products using label directions and service goals", "Explains pH limits accurately", "Recognizes referral and stop-service situations"],
        "avatar_bot": {"role": "Hair & Scalp Learning Guide", "allowed": ["Explain approved course concepts", "Prompt observation practice", "Compare approved cosmetic product categories", "Remind learners about referral boundaries"], "prohibited": ["Diagnose scalp disease", "Invent scalp pH from images", "Prescribe medication", "Promise cures", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Hair & Scalp Cosmetic Assessment", "sections": ["LOOK: density, texture, porosity clues, breakage, dryness, oiliness, flakes, buildup, redness.", "ASK: prior services, sensitivities, reactions, comfort, home-care products.", "SELECT: cosmetic cleansing/conditioning products from manufacturer directions and service goals.", "pH: use reliable product information or measurement; never guess a pH value from a photo.", "REFER: postpone when findings are concerning, unexplained, painful, inflamed, injured, or outside cosmetic scope."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "This lesson is educational and does not authorize medical diagnosis or treatment. Camera and AI tools may support documentation but must not diagnose disease or fabricate pH measurements."
    },
    "cosmetology-scalp-camera-assessment": {
        "summary": "Use standardized scalp photography and AI-assisted cosmetic observations to document visible changes while protecting consent, privacy, and professional scope.",
        "scope": "The camera and AI layer is a documentation and education aid. It may flag visible cosmetic patterns for human review but may not diagnose disease, prescribe treatment, or claim a chemical pH reading from an image.",
        "estimated_minutes": 90,
        "prerequisites": ["Cosmetology Foundations", "Hair & Scalp Science"],
        "materials": ["Approved camera or scalp imaging device", "Device cleaning supplies", "Consistent light source", "Consent form", "Secure client record", "Image comparison worksheet"],
        "objectives": ["Obtain informed permission before imaging.", "Capture repeatable scalp images.", "Document visible dryness, oiliness, flakes, buildup, breakage, density patterns, and redness neutrally.", "Use AI suggestions as review prompts rather than diagnoses.", "Protect image privacy and know when to refer."],
        "lesson_sections": [
            {"title": "Consent and privacy", "content": "Before taking a client image, explain why the image is being captured, where it will be stored, who may access it, and whether it will be used for teaching or comparison. Follow CrownPath privacy controls and applicable law. Do not use client images outside the approved purpose."},
            {"title": "Standardized image capture", "content": "Comparable images require repeatable lighting, distance, angle, magnification, parting pattern, and device cleanliness. Label images by date and approved scalp region rather than relying on memory. Poor image quality should be retaken rather than interpreted aggressively."},
            {"title": "AI-assisted cosmetic observations", "content": "CrownPath may be designed to highlight visible patterns such as apparent flakes, shine/oiliness, dryness, product buildup, breakage, or changes in visible density. These outputs should be phrased as observations or confidence-limited flags for a qualified human to review. The system must not convert a visual pattern into a medical diagnosis."},
            {"title": "Conditioning and care suggestions", "content": "When the visible observation remains within cosmetic scope, the system may support general product-category education such as gentle cleansing, rinse-out conditioning, leave-in conditioning, reduced heat, lower-friction handling, or protective styling. Product selection should remain tied to manufacturer directions, client history, practitioner judgment, and legal scope."},
            {"title": "Escalation", "content": "The practitioner should stop relying on cosmetic recommendations when images show or the client reports concerning pain, open injury, bleeding, severe inflammation, rapid unexplained change, or another issue outside scope. The appropriate action is referral, not automated diagnosis."}
        ],
        "steps": ["Explain the imaging process, privacy handling, and obtain permission.", "Capture comparable views using clean equipment and consistent lighting.", "Record objective visible observations and relevant client-reported history.", "Use the findings to select cosmetic conditioning, cleansing, protective-care, or referral options within scope."],
        "demonstration": {"title": "Standardized scalp-image session", "instructions": ["Show consent and privacy explanation.", "Clean the device and establish fixed lighting and distance.", "Capture the same scalp regions using a repeatable sequence.", "Review an example AI flag and restate it as a neutral observation requiring human review.", "Compare current and prior images without claiming diagnosis or pH measurement."]},
        "guided_practice": ["Learners capture a standardized image set on a mannequin or consenting model.", "Learners identify image-quality problems before interpreting the image.", "Learners write neutral cosmetic observations from sample images.", "Learners choose between proceed, modify, postpone/refer scenarios and explain why."],
        "knowledge_check": [
            {"question": "What should AI do when it detects a visual pattern that could have several causes?", "options": ["Name the disease", "Flag the visible pattern for human review and stay within cosmetic language", "Prescribe a treatment", "Automatically publish the client's image"], "answer_index": 1, "rationale": "AI should support observation and review, not diagnose."},
            {"question": "Why use consistent lighting and distance?", "options": ["To make images comparable over time", "To determine exact scalp pH", "To avoid obtaining consent", "To authorize medical treatment"], "answer_index": 0, "rationale": "Standardization improves useful visual comparison."}
        ],
        "practical_checkoff": ["Explains consent and privacy", "Cleans imaging equipment", "Uses consistent capture sequence", "Rejects poor-quality images", "Documents neutral observations", "Does not infer disease or pH", "Uses appropriate referral language"],
        "avatar_bot": {"role": "Scalp Camera Coach", "allowed": ["Guide image-capture sequence", "Check image-quality criteria", "Describe approved visible cosmetic categories", "Suggest approved educational product categories", "Prompt referral when configured safety boundaries are met"], "prohibited": ["Diagnose disease", "Generate medical treatment plans", "Claim exact pH from an image", "Override practitioner or Owner controls", "Expose client images without authorization"]},
        "student_handout": {"title": "Scalp Camera: Capture, Observe, Decide", "sections": ["CONSENT before capture.", "STANDARDIZE lighting, distance, angle, region, and device cleanliness.", "OBSERVE visible cosmetic characteristics only.", "AI FLAGS are prompts for human review, not diagnoses.", "pH cannot be reliably read from a photograph.", "PROCEED, MODIFY, or REFER based on scope, safety, history, and visible findings."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Imaging and AI assistance do not diagnose scalp disease, determine medical treatment, or replace licensed healthcare evaluation."
    },
}


def get_advanced_lesson_content(lesson_id: str):
    return ADVANCED_LESSON_CONTENT.get(lesson_id)
