BARBER_CORE_LESSON_CONTENT = {
    "barber-foundations": {
        "summary": "Establish professional barbering habits for workstation preparation, sanitation, consultation, client protection, tool selection, ergonomics, service planning, and professional closeout.",
        "scope": "General barber education. Current state barber-board rules, product directions, and lawful scope control where more specific.",
        "estimated_minutes": 120,
        "prerequisites": ["CrownPath professional conduct orientation"],
        "materials": ["Barber chair or practice station", "Clean clippers/trimmers and guards", "Combs and brushes", "Cape and client protection supplies", "Sanitation/disinfection supplies", "Consultation form", "Mannequin or consenting model"],
        "objectives": ["Prepare a clean and organized barber station.", "Conduct a structured consultation.", "Select appropriate tools for the planned service.", "Use client protection and ergonomic work habits.", "Complete service cleanup and documentation."],
        "lesson_sections": [
            {"title": "Professional station setup", "content": "Begin with a clean work area, required disinfected tools, protected clean storage, organized cords, appropriate lighting, and clear separation between clean and used items. Only prepare equipment needed for the planned service."},
            {"title": "Client consultation", "content": "Confirm the requested style, length, maintenance preferences, prior service history, sensitivities, and visible hair/scalp condition. Clarify terms with visual references or specific measurements when useful. Do not diagnose scalp disease."},
            {"title": "Tool knowledge and selection", "content": "Clippers, trimmers, guards, combs, brushes, shears, razors where lawful, and finishing tools serve different purposes. Select tools based on the service plan and manufacturer instructions. Inspect tools before use and remove damaged equipment from service."},
            {"title": "Client protection and comfort", "content": "Use clean capes and required neck protection, maintain safe tool temperature and pressure, manage loose hair, and communicate before repositioning the chair or client. Monitor comfort throughout the service."},
            {"title": "Body mechanics and control", "content": "Use stable stance, neutral wrist positions when possible, controlled tool movement, and appropriate chair height. Good ergonomics supports precision and reduces unnecessary strain."},
            {"title": "Service closeout", "content": "Inspect the result with the client, provide general grooming and maintenance guidance, remove loose hair safely, process reusable tools according to requirements, dispose of single-use items correctly, and reset the station."}
        ],
        "steps": ["Sanitize the station and prepare clean tools.", "Discuss the desired result and inspect visible hair/scalp condition.", "Choose guards, combs, brushes, and products appropriate to the service.", "Maintain tool control and client comfort throughout the service."],
        "demonstration": {"title": "Barber service setup", "instructions": ["Prepare and identify clean versus used zones.", "Conduct a concise consultation.", "Inspect and select clippers, guards, combs, and finishing tools.", "Demonstrate client protection and safe chair positioning.", "Close the mock service with tool processing and station reset."]},
        "guided_practice": ["Learners set up a barber station from a checklist.", "Learners role-play a consultation using specific style and length language.", "Learners match tools to common service tasks.", "Learners demonstrate safe closeout and reset."],
        "knowledge_check": [
            {"question": "When should a barber inspect tools?", "options": ["Before use", "Only after they fail", "Once a year", "Only when a client asks"], "answer_index": 0, "rationale": "Pre-service inspection helps identify damaged or unsafe equipment before client contact."},
            {"question": "Which consultation statement stays within barber scope?", "options": ["I can see visible flaking and redness, so we may need to modify or postpone service", "You definitely have psoriasis", "This product will cure your scalp", "The camera gives a medical diagnosis"], "answer_index": 0, "rationale": "Neutral visible observation supports safe service planning without diagnosis."}
        ],
        "practical_checkoff": ["Prepares clean station", "Separates clean and used items", "Conducts consultation", "Selects tools appropriately", "Protects client", "Uses controlled ergonomics", "Monitors comfort", "Completes cleanup/reset"],
        "avatar_bot": {"role": "Barber Foundations Coach", "allowed": ["Guide setup checklists", "Practice consultations", "Teach approved tool-purpose concepts", "Prompt sanitation and closeout"], "prohibited": ["Diagnose scalp disease", "Override sanitation rules", "Authorize out-of-scope services", "Reveal instructor answer keys"]},
        "student_handout": {"title": "Barber Foundations Service Flow", "sections": ["SET UP: clean station, tools, lighting and client protection.", "CONSULT: style, length, history, sensitivities and visible condition.", "SELECT: correct tools, guards and products.", "SERVE: control, ergonomics, comfort and communication.", "FINISH: inspect, educate, process tools and reset."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Follow current state-board sanitation, scope-of-practice, licensing rules, and manufacturer directions."
    },
    "barber-cutting-grooming": {
        "summary": "Develop a repeatable barber cutting and grooming process using consultation, shape planning, guides, clipper and shear control, fading/blending, perimeter detailing, facial-hair grooming where lawful, cross-checking, styling, and finish inspection.",
        "scope": "Barber cutting and grooming education within lawful scope. Sharp tools and razors must be used only when permitted, trained, and handled according to applicable rules and manufacturer instructions.",
        "estimated_minutes": 210,
        "prerequisites": ["Barber Foundations", "Barber Hair & Scalp"],
        "materials": ["Mannequin or consenting model", "Clippers and trimmers", "Guards", "Barber combs", "Shears", "Razor only where lawful/instructor-approved", "Brushes", "Cape and client protection", "Finishing products", "Sanitation supplies"],
        "objectives": ["Translate consultation into a cutting plan.", "Establish and follow guides consistently.", "Use clipper, comb, shear, and blending techniques with control.", "Create and refine fades/tapers and perimeters.", "Cross-check balance and finish the service systematically."],
        "lesson_sections": [
            {"title": "Plan before cutting", "content": "Identify the target silhouette, length, weight distribution, perimeter, fade or taper height, blend zones, growth patterns, and styling goal before removing significant hair. Confirm ambiguous requests before proceeding."},
            {"title": "Guides and section control", "content": "A guide creates a repeatable reference for length. Establish the first guide deliberately and keep sections small enough to see the reference. Losing the guide increases inconsistency."},
            {"title": "Clipper and guard control", "content": "Use the selected guard and clipper position according to the planned length. Work with controlled strokes, account for growth direction, and avoid repeated aggressive passes over sensitive areas. Keep blades maintained and monitor heat."},
            {"title": "Fading and blending", "content": "Build a fade or taper through planned zones rather than random removal. Establish the lower boundary, create transitional guides, then soften visible weight lines using appropriate guards, lever positions, clipper-over-comb, or other instructor-approved methods."},
            {"title": "Shear and comb work", "content": "Use consistent finger or comb elevation and controlled tension appropriate to the hair. Shear-over-comb and scissor work can refine weight and shape. Keep fingers and ears protected from the cutting path."},
            {"title": "Perimeter, line-up, and detailing", "content": "Refine the hairline and perimeter conservatively according to the consultation and natural growth pattern. Avoid unnecessarily pushing a natural hairline backward. Detail only after the major shape and blend are established."},
            {"title": "Facial-hair grooming", "content": "Where lawful, plan beard or mustache shape using symmetry, growth pattern, density, and client preference. Maintain sanitation and safe sharp-tool control. Do not perform services outside the practitioner's authorized scope."},
            {"title": "Cross-check and finish", "content": "Inspect from multiple angles and lighting positions. Check symmetry, transition zones, weight, perimeter, and client comfort. Apply finishing product sparingly according to the desired hold and finish and manufacturer directions."}
        ],
        "steps": ["Establish the shape, length, and first guide.", "Work methodically through sections or fade zones.", "Cross-check balance and blend transitions.", "Detail the perimeter and finish according to the consultation."],
        "demonstration": {"title": "Structured taper/fade and finish", "instructions": ["Translate a consultation into a zone and length plan.", "Establish the first guide and demonstrate controlled clipper passes.", "Create transition zones and remove visible weight lines methodically.", "Refine shape with comb/shear techniques where appropriate.", "Detail the perimeter conservatively, cross-check from multiple angles, and finish with an appropriate product."]},
        "guided_practice": ["Learners draw a cutting map before beginning.", "Learners establish and maintain a visible guide on a mannequin.", "Learners practice blending one controlled transition zone at a time.", "Learners cross-check a completed shape and identify remaining imbalance before detailing."],
        "knowledge_check": [
            {"question": "Why establish a guide before removing large amounts of hair?", "options": ["It provides a repeatable length reference", "It makes sanitation unnecessary", "It diagnoses scalp problems", "It replaces consultation"], "answer_index": 0, "rationale": "A clear guide supports consistent length and shape."},
            {"question": "When should perimeter detailing normally occur?", "options": ["Before planning the shape", "After the major shape and blend are established", "Before consultation", "Only after applying heavy product"], "answer_index": 1, "rationale": "Detailing is most controlled after the primary shape and transitions are established."},
            {"question": "What should a barber do if a clipper blade becomes uncomfortably hot?", "options": ["Keep using it", "Stop contact and follow safe cooling/maintenance procedures", "Press harder", "Cover the heat with product"], "answer_index": 1, "rationale": "Client comfort and burn prevention require stopping unsafe hot-blade contact."}
        ],
        "practical_checkoff": ["Creates cutting plan", "Establishes guide", "Controls clipper/guard use", "Builds fade zones methodically", "Uses comb/shear safely", "Protects ears/skin", "Details perimeter conservatively", "Cross-checks balance", "Finishes and sanitizes"],
        "avatar_bot": {"role": "Barber Cutting Coach", "allowed": ["Explain approved cutting sequences", "Prompt cutting-map planning", "Coach guide and cross-check concepts", "Provide practice scenarios"], "prohibited": ["Override instructor safety decisions", "Authorize prohibited razor use", "Diagnose hair/scalp disease", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Barber Cutting Sequence", "sections": ["PLAN: silhouette, length, fade/taper zones, growth pattern and perimeter.", "GUIDE: establish a clear reference before removing length.", "BUILD: work through sections/zones methodically.", "BLEND: soften transitions with controlled technique.", "DETAIL: refine perimeter after the main shape is established.", "CHECK: multiple angles, symmetry, comfort and finish."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Keep blades, clippers, shears, razors, and other sharp tools maintained and use them only as intended and within lawful scope."
    },
    "barber-consultation-safety": {
        "summary": "Integrate consultation, sanitation, infection-control awareness, tool and electrical safety, client protection, visible contraindication screening, unexpected-event response, documentation, and station reset into every barber service.",
        "scope": "General barber consultation and safety education. Official state requirements, product directions, workplace procedures, and emergency protocols control where more specific.",
        "estimated_minutes": 120,
        "prerequisites": ["Barber Foundations"],
        "materials": ["Consultation form", "Tool safety checklist", "Disinfection products used according to label", "Client protection supplies", "Incident/concern documentation form", "Electrical equipment inspection checklist", "Emergency procedure information"],
        "objectives": ["Confirm service expectations and relevant history.", "Identify visible conditions that require modification or referral without diagnosis.", "Inspect tools, cords, surfaces, and client protection before service.", "Respond appropriately to cuts, reactions, discomfort, or equipment problems.", "Complete sanitation, documentation, and reset."],
        "lesson_sections": [
            {"title": "Consultation as a safety control", "content": "A consultation is not only about style. Ask about relevant sensitivities, prior reactions, recent services, discomfort, and the requested result. Observe visible hair/scalp condition and clarify whether the planned service remains appropriate."},
            {"title": "Visible stop or modify conditions", "content": "Open injury, active bleeding, severe inflammation, significant pain, or another concerning out-of-scope finding may require modification, postponement, or referral. Describe visible findings neutrally rather than naming a disease."},
            {"title": "Tool and electrical inspection", "content": "Inspect clipper/trimmer condition, guards, blades, shears, cords, plugs, and other equipment before use. Remove damaged equipment from service. Keep electrical equipment away from unsafe moisture conditions and follow manufacturer instructions."},
            {"title": "Client protection", "content": "Use required clean capes, neck protection, towels, barriers, and eye/skin protection appropriate to the service. Manage blade temperature, pressure, chair position, and loose hair to maintain comfort and safety."},
            {"title": "Unexpected event response", "content": "Stop the relevant activity when a cut, unexpected reaction, significant discomfort, equipment failure, or other safety issue occurs. Follow the applicable blood-exposure, first-aid, product-response, emergency, and reporting procedures. Do not improvise medical treatment."},
            {"title": "Cleaning, disinfection, storage, and disposal", "content": "Process reusable tools and surfaces using the correct cleaning/disinfection sequence and product contact time. Dispose of single-use or contaminated items according to applicable requirements. Store clean tools to prevent recontamination."},
            {"title": "Documentation and reset", "content": "Record incidents or relevant service concerns factually when required. Reset the station only after used items have been removed and reusable equipment has been properly processed."}
        ],
        "steps": ["Confirm desired style and relevant service history.", "Check tools, cords, surfaces, and client protection.", "Monitor comfort and stop if an unexpected reaction occurs.", "Clean, disinfect, store tools, and reset the workstation."],
        "demonstration": {"title": "Pre-service safety and incident response", "instructions": ["Conduct a consultation that includes service and safety questions.", "Inspect electrical and sharp tools before use.", "Demonstrate client protection and temperature/comfort checks.", "Run a mock unexpected-event stop response using the approved workplace procedure.", "Demonstrate correct cleanup, disinfection contact-time awareness, storage, documentation, and reset."]},
        "guided_practice": ["Learners complete a pre-service safety inspection.", "Learners classify sample visible findings as proceed, modify, or postpone/refer without diagnosing.", "Learners practice stopping a service after a simulated unexpected event.", "Learners demonstrate station reset after a mock service."],
        "knowledge_check": [
            {"question": "What should happen to damaged electrical barber equipment?", "options": ["Keep using it carefully", "Remove it from service and follow repair/replacement procedures", "Tape it while the client waits", "Use it only on short services"], "answer_index": 1, "rationale": "Damaged equipment should not remain in client service."},
            {"question": "Which statement is appropriate when a visible scalp concern is outside barber scope?", "options": ["I have diagnosed an infection", "I see a concern that makes it safer to postpone this service and recommend appropriate evaluation", "This product will cure it", "AI says no referral is needed"], "answer_index": 1, "rationale": "Neutral observation and safe referral stay within professional boundaries."},
            {"question": "Why must disinfectant contact time be followed?", "options": ["It is part of using the product according to its directions", "It is optional", "Shorter is always better", "Only appearance matters"], "answer_index": 0, "rationale": "Disinfection products must be used according to label directions, including required contact time."}
        ],
        "practical_checkoff": ["Conducts safety-focused consultation", "Recognizes modify/refer conditions", "Inspects tools and cords", "Uses client protection", "Monitors blade temperature/comfort", "Stops appropriately for unexpected events", "Processes tools/surfaces correctly", "Documents and resets station"],
        "avatar_bot": {"role": "Barber Safety Coach", "allowed": ["Prompt safety inspections", "Practice consultation scenarios", "Teach approved sanitation sequence", "Remind learners to follow official procedures and product labels"], "prohibited": ["Diagnose conditions", "Replace emergency procedures", "Override state-board requirements", "Reveal instructor answer keys"]},
        "student_handout": {"title": "Barber Consultation & Safety Check", "sections": ["ASK: style, history, sensitivities, reactions and comfort.", "LOOK: visible condition without diagnosis.", "INSPECT: tools, blades, guards, cords, surfaces and client protection.", "MONITOR: heat, pressure, comfort and unexpected reactions.", "STOP: follow approved procedures for injury, reaction, equipment failure or other safety event.", "RESET: clean, disinfect, store, dispose and document correctly."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Use product labels, manufacturer instructions, workplace procedures, and applicable state-board rules as controlling guidance."
    },
}


def get_barber_core_lesson_content(lesson_id: str):
    return BARBER_CORE_LESSON_CONTENT.get(lesson_id)
