BEAUTY_LESSON_CONTENT = {
    "cosmetology-makeup-artistry": {
        "summary": "Build a complete professional makeup service from consultation and sanitation through complexion, color design, finishing, photography awareness, removal, and client education.",
        "scope": "Cosmetic makeup education within lawful cosmetology scope. This unit does not diagnose or treat skin disease and does not authorize services outside the learner's license or jurisdiction.",
        "estimated_minutes": 150,
        "prerequisites": ["Cosmetology Foundations"],
        "materials": ["Consenting model or practice face chart", "Clean makeup brushes and tools", "Disposable applicators", "Palette or hygienic product-dispensing surface", "Complexion products", "Eye and lip products", "Sanitation supplies", "Client consultation form", "Manufacturer directions"],
        "objectives": ["Conduct a makeup consultation and visible cosmetic skin observation.", "Prevent cross-contamination during makeup application.", "Select complexion, eye, cheek, and lip products for the requested look.", "Use color, balance, proportion, texture, and finish intentionally.", "Recognize when makeup application should be modified, postponed, or referred."],
        "lesson_sections": [
            {"title": "Consultation and design", "content": "Confirm the occasion, desired intensity, preferred colors and finishes, sensitivities, contact-lens considerations, prior reactions, and removal expectations. Evaluate only visible cosmetic characteristics such as apparent dryness, oiliness, texture, or uneven tone. Do not diagnose skin conditions."},
            {"title": "Sanitation and product control", "content": "Clean hands and tools, separate clean and used items, and avoid contaminating shared cosmetics. Use disposable applicators or dispense product onto a clean palette when appropriate. Do not double-dip a used applicator into shared product. Follow product labels and applicable sanitation rules."},
            {"title": "Complexion preparation", "content": "Prepare the skin using products appropriate to the cosmetic goal and manufacturer directions. Select foundation and concealer by desired coverage, finish, and visible skin characteristics. Blend in controlled layers rather than masking texture with excessive product."},
            {"title": "Color and feature design", "content": "Use color relationships, placement, value, intensity, shape, and blending to support the requested look. Brow, eye, cheek, and lip choices should work together. Corrective makeup means visual balancing through cosmetic technique; it is not medical correction."},
            {"title": "Day, evening, special-event, and camera awareness", "content": "A day look generally uses controlled intensity and natural transitions, while evening and special-event looks may use stronger contrast, definition, or durability. For photography, inspect blending under relevant lighting and consider how texture and finish appear on camera without promising a flawless or digitally altered result."},
            {"title": "Service completion", "content": "Inspect symmetry and balance, invite feedback, document products when appropriate, explain safe removal and general cosmetic aftercare, dispose of single-use items, and clean reusable tools according to applicable rules."}
        ],
        "steps": ["Consult on desired look, sensitivities, product history, and visible skin condition.", "Prepare sanitized tools and hygienic product-dispensing methods.", "Apply complexion, color, eye and lip products in a planned sequence.", "Finish the look and explain safe removal and aftercare."],
        "demonstration": {"title": "Complete makeup service", "instructions": ["Demonstrate consultation and design planning before product application.", "Show hygienic dispensing and brush/applicator control.", "Build complexion coverage in light layers and explain finish selection.", "Demonstrate eye, cheek, brow, and lip placement while checking balance.", "Inspect the result under normal and camera-relevant lighting, then demonstrate service closeout and sanitation."]},
        "guided_practice": ["Learners create a face chart before application.", "Learners perform a sanitation setup and explain how cross-contamination is prevented.", "Learners complete a balanced day or special-event look on a mannequin/practice surface or consenting model.", "Learners explain when visible irritation, injury, or another concern would require postponement."],
        "knowledge_check": [
            {"question": "What is the safest approach to a shared cream product?", "options": ["Double-dip the same applicator", "Dispense product hygienically onto a clean palette when appropriate", "Let every client use the same finger", "Skip sanitation if the product looks clean"], "answer_index": 1, "rationale": "Hygienic dispensing helps reduce cross-contamination."},
            {"question": "What should a cosmetology learner do when the intended makeup area appears severely irritated or injured?", "options": ["Cover it heavily", "Proceed without mentioning it", "Postpone or modify the service and refer when appropriate", "Diagnose the condition"], "answer_index": 2, "rationale": "Unsafe or out-of-scope findings require a safety decision rather than diagnosis or concealment."},
            {"question": "Corrective makeup primarily means what?", "options": ["Medical treatment", "Visual balancing using cosmetic color and placement", "Diagnosing facial conditions", "Changing bone structure"], "answer_index": 1, "rationale": "Corrective cosmetic technique changes visual balance, not anatomy or health status."}
        ],
        "practical_checkoff": ["Completes consultation", "Maintains clean/used separation", "Uses hygienic product dispensing", "Selects complexion products appropriately", "Balances eye, cheek, brow, and lip design", "Monitors client comfort", "Completes removal/aftercare education and sanitation"],
        "avatar_bot": {"role": "Makeup Artistry Coach", "allowed": ["Teach approved color and placement concepts", "Guide sanitation sequence", "Prompt face-chart planning", "Coach service sequencing"], "prohibited": ["Diagnose skin conditions", "Recommend medical treatment", "Override sanitation rules", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Makeup Service Flow", "sections": ["CONSULT: occasion, look, sensitivities, reactions, preferences.", "SANITIZE: hands, tools, palette, disposables; prevent double-dipping.", "DESIGN: complexion, brows, eyes, cheeks, lips as one coordinated look.", "CHECK: comfort, balance, blending, lighting and camera appearance.", "FINISH: feedback, removal guidance, documentation when appropriate, disposal and sanitation."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Do not apply cosmetics over conditions that appear infectious, severely irritated, injured, or otherwise unsafe for cosmetic service; refer when appropriate."
    },
    "cosmetology-nail-care": {
        "summary": "Teach professional manicure and pedicure foundations with consultation, visible nail observation, sanitation, shaping, cosmetic cuticle-area care, polish application, client comfort, and safe referral boundaries.",
        "scope": "Cosmetic nail-care education within lawful cosmetology scope. This unit does not diagnose or treat nail or skin disease and does not authorize medical foot care or services reserved to another credential.",
        "estimated_minutes": 150,
        "prerequisites": ["Cosmetology Foundations"],
        "materials": ["Consenting model or practice hand/foot", "Clean nail implements", "Single-use files/buffers as required", "Hand and foot sanitation supplies", "Bowls or service equipment where permitted", "Nail polish or approved cosmetic coatings", "Cotton/gauze and disposables", "Manufacturer directions", "Consultation form"],
        "objectives": ["Prepare a sanitary manicure or pedicure station.", "Conduct a nail consultation and neutral visible observation.", "Shape and groom nails without damaging living tissue.", "Apply cosmetic nail products according to directions.", "Recognize conditions that require service modification, postponement, or referral."],
        "lesson_sections": [
            {"title": "Consultation and visible nail observation", "content": "Ask about the requested service, sensitivities, prior reactions, recent nail services, discomfort, and relevant history. Observe nail length, shape, visible surface condition, surrounding skin, and any obvious injury or irritation. Describe what is visible without diagnosing fungus, infection, or another disease."},
            {"title": "Sanitation and infection-control workflow", "content": "Prepare the station before the client service. Follow applicable requirements for hand hygiene, reusable implement cleaning/disinfection, single-use items, surfaces, bowls, foot-service equipment, and product handling. Keep clean items separate from used or contaminated items."},
            {"title": "Natural nail shaping and cosmetic care", "content": "Choose a shape compatible with the client's goals and natural nail condition. File with controlled pressure and avoid aggressive thinning. Care around the cuticle and surrounding skin must remain within legal cosmetic scope and should not intentionally injure living tissue."},
            {"title": "Manicure and pedicure service sequencing", "content": "Use an organized sequence for preparation, shaping, cosmetic surrounding-skin care, product application, finishing, and cleanup. Monitor temperature, pressure, comfort, and skin condition throughout a pedicure. Never use a routine cosmetic service as a substitute for medical foot care."},
            {"title": "Polish and cosmetic coatings", "content": "Prepare the nail surface as directed by the product manufacturer and apply base, color, topcoat, or other permitted cosmetic systems in controlled layers. Follow cure times, lamp instructions, removal procedures, ventilation requirements, and allergy/sensitivity warnings when applicable."},
            {"title": "When not to proceed", "content": "Postpone or modify the service when there is an open wound, bleeding, severe inflammation, significant pain, or another visible concern outside cosmetic scope. Do not attempt to diagnose or treat a suspected nail or skin disease. Use appropriate referral language."}
        ],
        "steps": ["Consult, inspect visible nail and surrounding skin condition, and prepare sanitized implements.", "Shape and care for nails and surrounding cosmetic areas without cutting living tissue beyond lawful scope.", "Apply permitted cosmetic products using manufacturer directions and hygienic practices.", "Clean and disinfect reusable implements and surfaces, dispose of single-use items, and explain home maintenance."],
        "demonstration": {"title": "Complete basic manicure/pedicure workflow", "instructions": ["Show station setup and client consultation.", "Demonstrate neutral nail and surrounding-skin observation.", "Demonstrate controlled shaping and cosmetic cuticle-area care without aggressive tissue removal.", "Apply an approved polish system according to manufacturer directions.", "Demonstrate cleanup, disposal, reusable implement processing, and general home-maintenance guidance."]},
        "guided_practice": ["Learners prepare and pass a sanitation station check before beginning.", "Learners practice nail-shape selection and controlled filing.", "Learners perform an instructor-approved manicure or pedicure sequence on a practice aid or consenting model.", "Learners identify referral scenarios from instructor-provided examples."],
        "knowledge_check": [
            {"question": "Which statement stays within cosmetic nail-care scope?", "options": ["This nail has a fungal infection", "I see a visible change that is outside this cosmetic service, so I recommend postponing and seeking appropriate evaluation", "This product will cure the nail", "A pedicure replaces medical foot care"], "answer_index": 1, "rationale": "The learner may describe visible findings and make a safe service decision without diagnosis."},
            {"question": "What should happen to a single-use item after the service when applicable rules require disposal?", "options": ["Return it to the clean drawer", "Use it on the next client", "Dispose of it according to the required process", "Share it with another station"], "answer_index": 2, "rationale": "Single-use items must not be treated as reusable when rules or manufacturer directions require disposal."},
            {"question": "What controls curing or removal of a cosmetic nail product?", "options": ["Guesswork", "Manufacturer directions and applicable rules", "Social-media comments", "The fastest possible method"], "answer_index": 1, "rationale": "Product systems should be used according to their instructions and applicable requirements."}
        ],
        "practical_checkoff": ["Prepares sanitary station", "Completes consultation and neutral observation", "Uses controlled shaping", "Avoids intentional injury to living tissue", "Follows product directions", "Maintains client comfort", "Recognizes stop/referral scenarios", "Completes disposal, cleaning, disinfection, and reset"],
        "avatar_bot": {"role": "Nail Care Learning Coach", "allowed": ["Guide service sequence", "Prompt sanitation checks", "Teach approved nail-shape and polish concepts", "Practice referral scenarios"], "prohibited": ["Diagnose nail disease", "Recommend medical treatment", "Authorize out-of-scope foot care", "Override manufacturer directions or official rules", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Nail Care Safety Flow", "sections": ["CONSULT and LOOK: requested service, sensitivities, discomfort, nail and surrounding-skin condition.", "SANITIZE: hands, station, reusable implements and equipment; manage single-use items correctly.", "SHAPE: controlled filing and cosmetic care without intentional injury.", "APPLY: follow manufacturer directions for coatings, cure, ventilation and removal.", "STOP/REFER: open wounds, bleeding, severe inflammation, significant pain, or out-of-scope concerns.", "RESET: dispose, clean, disinfect and prepare for the next client."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Never diagnose or treat nail disease. Follow current state scope-of-practice rules, infection-control requirements, and manufacturer directions."
    },
}


def get_beauty_lesson_content(lesson_id: str):
    return BEAUTY_LESSON_CONTENT.get(lesson_id)
