COSMETOLOGY_CORE_LESSON_CONTENT = {
    "cosmetology-chemical-safety": {
        "summary": "Build disciplined chemical-service safety habits for consultation, manufacturer instructions, preliminary testing, product handling, ventilation, PPE, timing, monitoring, emergency response, cleanup, and documentation.",
        "scope": "Cosmetology chemical-safety education only. Product labels, manufacturer instructions, applicable law, and current licensing rules control. This unit does not authorize medical diagnosis or treatment and does not replace product-specific training.",
        "estimated_minutes": 150,
        "prerequisites": ["Cosmetology Foundations", "Hair & Scalp Science"],
        "materials": ["Manufacturer instructions and safety information for instructor-approved products", "Gloves and other required PPE", "Client consultation record", "Preliminary/patch/strand test documentation where applicable", "Timer", "Ventilated training area", "Clean applicators and containers", "Emergency rinse access appropriate to the training setting", "Sanitation supplies"],
        "objectives": ["Read and follow manufacturer directions before chemical service.", "Conduct consultation and required preliminary testing.", "Use PPE, ventilation, mixing, application, and timing controls.", "Recognize adverse reactions and stop-service conditions.", "Document the service and safely handle cleanup and disposal."],
        "lesson_sections": [
            {"title": "Consultation before chemistry", "content": "Confirm the requested service, relevant prior chemical services, sensitivities, previous reactions, visible hair/scalp condition, and product history within professional scope. Do not guess about compatibility when information is missing. Postpone when the product instructions or visible condition indicate the service should not proceed."},
            {"title": "Manufacturer instructions are controlling", "content": "Read the complete instructions for the exact product system before mixing or applying. Follow specified ratios, developer or activator requirements, processing limits, application sequence, testing, PPE, ventilation, and removal steps. CrownPath does not encourage improvised mixtures or substitutions that conflict with the manufacturer."},
            {"title": "Preliminary, patch, allergy-alert, and strand testing", "content": "Perform tests whenever required by the manufacturer or applicable rules. Different products use different test methods and timing, so the course should not invent a universal procedure. Record required results and do not treat a passed test as a guarantee that no reaction can occur."},
            {"title": "Mixing and contamination control", "content": "Use clean, compatible containers and applicators as directed. Measure accurately, avoid cross-contamination, label or identify prepared mixtures as needed in the training workflow, and never return used or mixed product to a clean stock container unless the manufacturer explicitly permits it."},
            {"title": "Application, timing, and monitoring", "content": "Protect the client and surrounding surfaces, use the correct application sequence, start timing as directed, and monitor comfort and visible response. More time or stronger chemistry is not automatically better. Never exceed labeled processing limits to chase a result."},
            {"title": "Adverse reaction response", "content": "If the client reports significant burning, breathing difficulty, swelling, severe discomfort, or another concerning reaction, stop the service and follow the product's immediate-response directions. Rinse or remove product when instructed and seek appropriate emergency or professional care when indicated. Do not attempt to diagnose the reaction."},
            {"title": "Ventilation, storage, cleanup, and disposal", "content": "Maintain required ventilation, close and store products as directed, clean applicable tools and surfaces, and dispose of chemical waste according to product directions and applicable requirements. Keep incompatible products separated when required."},
            {"title": "Documentation and future service planning", "content": "Record the products used, relevant formulation details permitted by the business workflow, timing, tests, observations, unexpected events, and client-care instructions. Documentation supports safer future consultation but does not replace a fresh assessment at the next visit."}
        ],
        "steps": ["Read the full manufacturer instructions before mixing or applying.", "Perform required consultation and preliminary testing.", "Use ventilation, protection, timing, and application controls.", "Stop, rinse, or escalate according to instructions if an adverse reaction occurs."],
        "demonstration": {"title": "Chemical-service safety setup", "instructions": ["Review an instructor-approved product label and identify required PPE, ratio, timing, tests, and warnings.", "Demonstrate consultation documentation and a product-specific preliminary test only according to its directions.", "Set up clean measuring, mixing, timing, and client-protection controls.", "Walk through a simulated application and monitoring sequence without exceeding product directions.", "Run a mock adverse-reaction response and complete cleanup/documentation."]},
        "guided_practice": ["Learners extract safety requirements from an instructor-approved manufacturer instruction sheet.", "Learners build a pre-service checklist without inventing missing product instructions.", "Learners identify unsafe mixing, timing, ventilation, or PPE scenarios.", "Learners practice stop-service communication for a simulated adverse reaction."],
        "knowledge_check": [
            {"question": "What controls the mixing ratio for a professional chemical product?", "options": ["The practitioner's guess", "Manufacturer directions for the exact product system", "A social-media comment", "Whatever produces the fastest result"], "answer_index": 1, "rationale": "The exact manufacturer's directions control product preparation and use."},
            {"question": "Does a passed preliminary test guarantee that no reaction can occur?", "options": ["Yes", "No", "Only for color", "Only when AI approves it"], "answer_index": 1, "rationale": "Required tests reduce risk or screen for specified concerns but do not guarantee that an adverse reaction is impossible."},
            {"question": "What should happen when a client reports a serious unexpected burning sensation during processing?", "options": ["Increase processing time", "Ignore it", "Stop and follow the product's immediate-response directions, escalating care when indicated", "Add another chemical"], "answer_index": 2, "rationale": "Unexpected significant reactions require prompt safety action, not stronger or longer processing."}
        ],
        "practical_checkoff": ["Reads exact manufacturer instructions", "Completes consultation", "Identifies required testing", "Uses PPE and ventilation", "Measures/mixes according to directions", "Uses correct timing", "Monitors client response", "Demonstrates stop-response procedure", "Completes cleanup and documentation"],
        "avatar_bot": {"role": "Chemical Safety Coach", "allowed": ["Prompt learners to read approved manufacturer instructions", "Quiz safety sequencing", "Remind learners about PPE, timing, ventilation, and escalation", "Explain general chemical-safety concepts"], "prohibited": ["Invent mixing ratios", "Recommend improvised chemical combinations", "Override product warnings", "Diagnose reactions", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Chemical Service Safety", "sections": ["READ the exact product directions first.", "CONSULT: history, sensitivities, prior reactions, visible condition and service goal.", "TEST when required by manufacturer or applicable rules.", "CONTROL: PPE, ventilation, measurement, mixing, application and timing.", "MONITOR: comfort and visible response; never exceed directions to chase a result.", "STOP: follow immediate-response directions for adverse reactions and seek appropriate care when indicated.", "DOCUMENT and safely clean/store/dispose after service."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Never improvise chemical mixtures or exceed manufacturer directions. Product-specific instructions and applicable regulations take priority over general course guidance."
    },
    "cosmetology-hair-replacement": {
        "summary": "Teach non-surgical cosmetic hair-replacement fundamentals including consultation, system selection, sanitation, scalp and hair observation, fitting, lawful cosmetic attachment concepts, blending, maintenance, removal, documentation, and referral boundaries.",
        "scope": "Non-surgical cosmetic hair replacement only. This unit excludes hair transplantation, graft harvesting, skin incision, implantation into living tissue, anesthesia, medical diagnosis, medication, and other medical procedures. Lawful cosmetology scope varies by jurisdiction and attachment method.",
        "estimated_minutes": 180,
        "prerequisites": ["Cosmetology Foundations", "Hair & Scalp Science", "Scalp Camera/AI Assessment"],
        "materials": ["Mannequin or consenting model", "Instructor-approved non-surgical hair system or practice piece", "Clean combs and sectioning tools", "Sanitation supplies", "Manufacturer directions for the selected system and attachment products", "Client consultation and maintenance forms", "Approved scalp imaging tool if used", "Removal products specified by the system manufacturer when applicable"],
        "objectives": ["Distinguish non-surgical cosmetic hair replacement from surgical transplantation.", "Conduct consultation and visible scalp/hair observation without diagnosis.", "Compare general non-surgical system and attachment categories within legal scope.", "Fit, blend, maintain, and remove an instructor-approved practice system according to manufacturer directions.", "Recognize when service should be postponed or referred."],
        "lesson_sections": [
            {"title": "Cosmetic versus surgical hair replacement", "content": "A cosmetic hair system adds or replaces the appearance of hair without surgically moving follicles into living tissue. CrownPath may teach wigs, toppers, integration pieces, and other lawful non-surgical systems. It does not teach incision, graft extraction, graft placement, anesthesia, surgical implantation, or post-surgical medical management."},
            {"title": "Consultation and goals", "content": "Discuss coverage goals, desired density, texture, color, length, lifestyle, maintenance tolerance, budget expectations, sensitivities, prior system experience, and service history. Explain what the chosen cosmetic system can and cannot reasonably accomplish."},
            {"title": "Visible scalp and hair observation", "content": "Observe visible scalp condition, hair density, breakage, growth direction, and the areas requiring cosmetic coverage. Use neutral language. Scalp-camera or AI tools may document visible patterns but must not diagnose the cause of hair loss or determine a medical treatment plan."},
            {"title": "System categories and selection", "content": "Introduce general categories such as wigs, toppers, partial systems, integration systems, and other non-surgical cosmetic pieces appropriate to the training setting. Selection considers coverage, base design, hair type, color, density, lifestyle, maintenance, manufacturer requirements, and lawful scope."},
            {"title": "Attachment boundaries", "content": "Attachment may involve clips, tapes, adhesives, integration methods, or other cosmetic systems when lawful and supported by manufacturer instructions and practitioner training. Do not use a method merely because it is available online. Never penetrate living skin, implant hair into tissue, or perform a surgical technique in this course."},
            {"title": "Preparation, fitting, and blending", "content": "Prepare the natural hair, scalp surface, and system according to the selected product instructions. Fit without unnecessary tension or discomfort. Blend color, density, perimeter, length, and style conservatively so the system integrates with the client's goals while preserving safe removal and maintenance."},
            {"title": "Maintenance and removal", "content": "Explain cleaning, drying, detangling, heat limitations, product compatibility, attachment maintenance, scheduled removal or reapplication, and storage according to the specific system. Use the manufacturer's approved removal process and avoid force that can injure the scalp or natural hair."},
            {"title": "Referral and medical boundaries", "content": "Do not diagnose alopecia, infection, inflammatory disease, or the cause of hair loss. Concerning scalp findings, sudden unexplained hair loss, significant pain, open injury, or other out-of-scope concerns should be referred to an appropriate healthcare professional. A cosmetic system should not delay needed evaluation."},
            {"title": "Documentation and follow-up", "content": "Record the system type, approved attachment products, relevant maintenance schedule, client education, visible observations, and follow-up plan. If images are used, obtain permission and protect them as authorized client records."}
        ],
        "steps": ["Consult on goals, scalp condition, sensitivities, and the type of hair-replacement system.", "Clean and prepare the scalp and system according to product directions.", "Use only cosmetic attachment methods that are lawful within the practitioner's scope.", "Explain maintenance, removal, sanitation, and follow-up care."],
        "demonstration": {"title": "Non-surgical hair-system fitting", "instructions": ["Demonstrate consultation and neutral visible scalp/hair observation.", "Compare two instructor-approved cosmetic system categories and explain selection factors.", "Prepare a mannequin or consenting model and practice system according to manufacturer directions.", "Demonstrate a lawful non-surgical fitting/attachment concept without penetrating living tissue.", "Blend the system cosmetically, then demonstrate the approved maintenance/removal sequence and documentation."]},
        "guided_practice": ["Learners distinguish cosmetic systems from prohibited surgical procedures.", "Learners complete a system-selection worksheet using coverage, texture, density, color, lifestyle, and maintenance factors.", "Learners fit and blend an instructor-approved practice piece under supervision.", "Learners practice explaining maintenance and safe removal.", "Learners identify scenarios requiring medical referral rather than cosmetic attachment."],
        "knowledge_check": [
            {"question": "Which procedure is outside CrownPath's non-surgical hair-replacement course?", "options": ["Fitting a topper", "Blending a wig", "Implanting harvested follicles through skin incisions", "Teaching system maintenance"], "answer_index": 2, "rationale": "Surgical transplantation and implantation into living tissue are medical procedures and are excluded."},
            {"question": "Can scalp-camera AI diagnose the cause of a client's hair loss?", "options": ["Yes", "No; it may support visible documentation but not medical diagnosis", "Only after a haircut", "Only if the client requests it"], "answer_index": 1, "rationale": "Visible imaging support does not establish a medical diagnosis."},
            {"question": "What should control removal of an adhesive or attachment system?", "options": ["Pulling until it releases", "Manufacturer directions, lawful scope, and appropriate approved removal products", "The fastest method online", "An improvised solvent"], "answer_index": 1, "rationale": "Safe removal follows the system instructions and professional scope rather than force or improvisation."}
        ],
        "practical_checkoff": ["Explains non-surgical scope", "Completes consultation", "Uses neutral scalp/hair observation", "Selects appropriate practice system", "Follows manufacturer preparation", "Uses only lawful cosmetic attachment", "Fits without unnecessary tension", "Blends appropriately", "Explains maintenance/removal", "Recognizes referral scenarios"],
        "avatar_bot": {"role": "Hair Replacement Learning Coach", "allowed": ["Teach approved non-surgical system concepts", "Guide consultation and maintenance checklists", "Compare approved cosmetic system categories", "Prompt referral boundaries"], "prohibited": ["Teach surgical transplantation", "Diagnose hair-loss causes", "Recommend medication", "Authorize out-of-scope attachment methods", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Non-Surgical Hair Replacement", "sections": ["COSMETIC ONLY: wigs, toppers and lawful non-surgical systems; no incision, graft harvesting, implantation or anesthesia.", "CONSULT: coverage, style, density, texture, color, lifestyle, sensitivities and maintenance.", "OBSERVE: visible scalp/hair condition neutrally; camera/AI does not diagnose hair loss.", "SELECT: system and attachment based on manufacturer directions, training and lawful scope.", "FIT/BLEND: protect comfort, natural hair and scalp; avoid unnecessary tension.", "MAINTAIN/REMOVE: follow the specific system directions and approved products.", "REFER: sudden unexplained loss, significant pain, open injury or concerning out-of-scope findings."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "CrownPath does not teach or authorize surgical implantation, skin incision, graft harvesting, anesthesia, medical diagnosis, or other medical procedures."
    },
}


def get_cosmetology_core_lesson_content(lesson_id: str):
    return COSMETOLOGY_CORE_LESSON_CONTENT.get(lesson_id)
