EXPERIENCE_AGENT_LESSON_CONTENT = {
    "wellness-client-experience": {
        "summary": "Design and deliver a respectful CrownPath client journey from booking through consultation, service coordination, payment handoff, feedback, follow-up, and issue resolution.",
        "scope": "Professional client-experience education across authorized CrownPath services. Each practitioner remains responsible for their own license, credential, training, privacy duties, and scope of practice.",
        "estimated_minutes": 120,
        "prerequisites": ["CrownPath professional conduct orientation"],
        "materials": ["Booking and consultation workflow", "Consent forms", "Accessibility and communication preference checklist", "Service handoff form", "Feedback form", "Complaint/escalation workflow", "Privacy policy summary"],
        "objectives": ["Map the complete client journey.", "Use clear consent, expectation-setting, and accessibility communication.", "Coordinate lawful handoffs between professionals.", "Protect client privacy during communication and records handling.", "Respond to complaints and service concerns professionally without making unsupported promises."],
        "lesson_sections": [
            {"title": "Booking and first contact", "content": "Capture only the information needed for the requested service, explain basic expectations, confirm communication preferences, identify accessibility needs, and avoid collecting unnecessary sensitive information. A professional first contact should make the next step clear without overselling results."},
            {"title": "Consultation and informed service consent", "content": "Before beginning, confirm the client's goal, service plan, relevant history within scope, limits, estimated time, price, and expected maintenance. Consent should be informed and specific to the service. The client may ask questions, decline, or stop a service."},
            {"title": "Coordinated service handoffs", "content": "When multiple authorized professionals are involved, transfer only the information needed for continuity and safety. Do not let one role perform tasks reserved to another role. The receiving professional should independently confirm the service plan and scope."},
            {"title": "Privacy and records", "content": "Client notes, images, preferences, communications, and service records should be available only to authorized people and systems. Never place client information into an avatar, bot, public channel, or marketing workflow unless the use is authorized and permitted."},
            {"title": "Comfort and accessibility", "content": "Use respectful language, plain explanations, appropriate seating or movement options, captions or text alternatives when available, and reasonable adjustments supported by the setting. Accessibility does not mean lowering safety or licensing standards; it means making authorized services easier to understand and use."},
            {"title": "Feedback and service recovery", "content": "Invite feedback without pressuring the client. When a concern arises, listen, document facts, acknowledge the issue, explain the available business process, and escalate when needed. Do not promise refunds, medical outcomes, credential decisions, or compensation beyond the authority of the person handling the interaction."},
            {"title": "Follow-up and retention", "content": "Follow-up may include approved aftercare reminders, maintenance scheduling, satisfaction checks, or educational resources. Marketing contact should follow consent and communication-preference rules. Retention should come from trust and service quality rather than pressure."}
        ],
        "steps": ["Confirm booking details, service goals, accessibility needs, and relevant preferences.", "Explain each service, expected experience, limits, price, and aftercare before beginning.", "Coordinate handoffs between authorized professionals while protecting client privacy.", "Collect feedback, document concerns, and schedule appropriate follow-up without making unsupported health claims."],
        "demonstration": {"title": "Client journey from booking to follow-up", "instructions": ["Demonstrate a concise booking interaction.", "Conduct a service consultation and consent check.", "Model a handoff from one authorized professional to another without oversharing client data.", "Respond to a mock complaint using factual documentation and escalation.", "Complete a follow-up message using approved communication preferences."]},
        "guided_practice": ["Learners map one complete CrownPath client journey.", "Learners role-play an accessibility request and identify reasonable communication adjustments.", "Learners practice a multi-service handoff while protecting privacy.", "Learners respond to a complaint scenario without making promises outside their authority."],
        "knowledge_check": [
            {"question": "What should be shared during a professional handoff?", "options": ["Every detail known about the client", "Only information needed for authorized continuity and safety", "Private information with anyone nearby", "Nothing, even when safety requires continuity"], "answer_index": 1, "rationale": "Handoffs should follow minimum-necessary privacy and role boundaries."},
            {"question": "What should happen when a client asks to stop a service?", "options": ["Continue until the scheduled end", "Respect the request and stop or safely conclude the service", "Ask a bot to decide", "Charge extra before stopping"], "answer_index": 1, "rationale": "Consent remains active and revocable during the service."},
            {"question": "Which complaint response is appropriate?", "options": ["Promise any refund immediately", "Document facts, explain the approved process, and escalate when needed", "Delete the complaint", "Blame another department"], "answer_index": 1, "rationale": "Professional service recovery follows authority, documentation, and escalation rules."}
        ],
        "practical_checkoff": ["Maps booking-to-follow-up workflow", "Explains service and obtains consent", "Uses respectful accessibility communication", "Protects privacy during handoff", "Documents feedback factually", "Uses escalation path appropriately", "Avoids unauthorized promises"],
        "avatar_bot": {"role": "Client Experience Coach", "allowed": ["Teach approved communication workflows", "Prompt consent and privacy checklists", "Practice complaint scenarios", "Suggest approved follow-up templates"], "prohibited": ["Promise refunds or compensation", "Make medical claims", "Change licenses or credentials", "Expose client records", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Client Journey", "sections": ["BOOK: clear service, time, price, preferences and accessibility needs.", "CONSULT: goals, limits, consent, relevant history and expectations.", "SERVE: comfort, privacy, professional scope and communication.", "HANDOFF: minimum necessary information to authorized people only.", "RECOVER: listen, document, explain process, escalate when required.", "FOLLOW UP: approved aftercare, maintenance, feedback and consent-based communication."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Each professional remains responsible for working within their own license, credential, training, privacy obligations, and applicable law."
    },
    "avatar-bot-builder-foundations": {
        "summary": "Teach authorized CrownPath users how to design, configure, test, approve, and safely deploy avatars and bots for education, instruction support, client assistance, accessibility, and Owner/admin workflows.",
        "scope": "Avatars and bots are controlled assistants. Configuration never grants permission beyond server-side authorization. Human review remains required for safety-sensitive, regulatory, credential, security, financial, and other reserved decisions.",
        "estimated_minutes": 150,
        "prerequisites": ["CrownPath professional conduct orientation", "Role and permission basics"],
        "materials": ["Avatar/Bot role worksheet", "Knowledge-source checklist", "Capability and prohibited-action matrix", "Language/voice/accessibility settings", "Test scenario pack", "Approval and publishing checklist", "Audit review form"],
        "objectives": ["Define a clear avatar or bot purpose before configuration.", "Assign approved knowledge and least-privilege permissions.", "Separate educational suggestions from authoritative actions.", "Configure privacy, escalation, accessibility, and human-approval boundaries.", "Test normal, uncertain, adversarial, safety-sensitive, and out-of-scope scenarios before publishing."],
        "lesson_sections": [
            {"title": "Choose the role", "content": "Start with one clear job such as Learner Guide, Instructor Assistant, Demonstration Coach, Client Service Assistant, Owner/Admin Assistant, Content Assistant, Regulatory Research Assistant, or Accessibility/Translation Assistant. A narrow role is easier to secure and evaluate than an unrestricted general-purpose bot."},
            {"title": "Approved knowledge sources", "content": "Ground the bot in CrownPath-approved curriculum, policies, and other authorized sources. Regulatory research assistants may summarize or draft from official sources but should not declare requirements current or verified without the required human review process. Learner bots must not receive instructor-only answer keys."},
            {"title": "Least-privilege permissions", "content": "Prompts and persona text do not create authority. Server-side permissions decide what a bot can read or change. Give each bot only the capabilities needed for its job. Separate read, draft, recommend, publish, approve, record-change, and external-communication capabilities."},
            {"title": "Safety and prohibited actions", "content": "CrownPath bots may not independently diagnose medical conditions, prescribe treatment, approve regulated credentials, override Owner or security controls, make financial decisions, or perform other decisions reserved for qualified humans. Safety-sensitive uncertainty should trigger escalation rather than confident guessing."},
            {"title": "Privacy and data boundaries", "content": "Limit access to client, learner, staff, and business records by role. Do not send protected or private data to unnecessary tools or public channels. Bots should identify when a task requires data they are not authorized to access and escalate instead of bypassing controls."},
            {"title": "Voice, language, avatar, and accessibility settings", "content": "Configure text, voice, visual avatar style, languages, captions, transcripts, keyboard-compatible controls, screen-reader labels, and reduced-motion options as appropriate. Translation of safety or regulatory material should be reviewed by a qualified human when accuracy is critical."},
            {"title": "Testing and red-team scenarios", "content": "Before publishing, test ordinary questions, ambiguous requests, requests for hidden answers, unsafe medical or regulatory questions, attempts to bypass permissions, privacy-sensitive prompts, and requests outside the bot's role. Record failures and fix the configuration or permissions before approval."},
            {"title": "Approval, publishing, monitoring, and audit", "content": "Publishing should require the appropriate authorized approval. Record who configured and approved the bot, its knowledge scope, permissions, version, and important changes. Monitor reports and failures so a bot can be disabled or corrected when necessary."}
        ],
        "steps": ["Choose the avatar or bot purpose, such as learner guide, instructor assistant, client helper, or Owner support.", "Assign the approved course areas, language, voice or text mode, and role-based permissions.", "Configure prohibited actions, escalation rules, privacy limits, and human-approval requirements.", "Test the avatar or bot against normal, uncertain, safety-sensitive, and out-of-scope questions before publishing."],
        "demonstration": {"title": "Build a CrownPath Learner Guide bot", "instructions": ["Define the bot's job and intended users.", "Assign only approved learner-facing course content.", "Set read-only learner permissions and explicitly prohibit answer-key access.", "Configure medical, regulatory, privacy, and security escalation rules.", "Enable captions/text alternatives and an approved language setting.", "Run normal and adversarial tests, document results, and require approval before publishing."]},
        "guided_practice": ["Learners design one bot role using the role worksheet.", "Learners separate allowed actions from prohibited actions.", "Learners choose approved knowledge sources and identify instructor-only material that must be excluded.", "Learners run a scenario pack including an answer-key request, medical-diagnosis request, permission-bypass attempt, and legitimate course question.", "Learners revise the design based on failures before mock approval."],
        "knowledge_check": [
            {"question": "What actually grants a CrownPath bot permission to change a protected record?", "options": ["Its personality prompt", "Server-side authorization and approved capabilities", "A confident response", "The avatar's visual style"], "answer_index": 1, "rationale": "Permissions must be enforced by the system, not by prompt wording."},
            {"question": "What should a learner bot do when asked for instructor-only quiz answers?", "options": ["Reveal them", "Refuse to expose restricted material and continue with permitted learning help", "Change the user's role", "Publish the answer key"], "answer_index": 1, "rationale": "Learner-facing bots must not expose instructor-only answer keys."},
            {"question": "What should a regulatory research bot do when official information is uncertain or not yet human-verified?", "options": ["Declare it final", "Clearly mark uncertainty and route it for qualified human verification", "Invent a rule", "Approve a credential"], "answer_index": 1, "rationale": "Regulatory conclusions require verified sources and appropriate human review."}
        ],
        "practical_checkoff": ["Defines a narrow role", "Assigns approved knowledge", "Uses least privilege", "Separates learner and instructor content", "Configures privacy limits", "Adds safety escalation", "Includes accessibility settings", "Tests adversarial scenarios", "Documents approval and versioning"],
        "avatar_bot": {"role": "Avatar & Bot Builder Coach", "allowed": ["Teach approved builder concepts", "Guide role and permission design", "Prompt safety testing", "Explain approval and audit requirements"], "prohibited": ["Grant itself new permissions", "Disable Owner/security controls", "Publish unapproved bots", "Expose restricted data or answer keys", "Make reserved medical, regulatory, credential, or financial decisions"]},
        "student_handout": {"title": "CrownPath Avatar & Bot Builder Checklist", "sections": ["ROLE: one clear job and intended audience.", "KNOWLEDGE: approved sources only; exclude restricted material.", "PERMISSIONS: least privilege; prompts never replace server authorization.", "BOUNDARIES: medical, regulatory, financial, credential, security and privacy limits.", "ACCESSIBILITY: language, captions, text alternatives, keyboard/screen-reader and reduced motion where appropriate.", "TEST: normal, uncertain, unsafe, privacy-sensitive and bypass attempts.", "APPROVE: authorized human review before publishing.", "AUDIT: record version, approver, permissions, changes and failures."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "CrownPath avatars and bots may educate and assist, but they must not independently diagnose medical conditions, approve regulated credentials, override security controls, make reserved financial decisions, or bypass qualified human review."
    },
}


def get_experience_agent_lesson_content(lesson_id: str):
    return EXPERIENCE_AGENT_LESSON_CONTENT.get(lesson_id)
