WELLNESS_LESSON_CONTENT = {
    "wellness-massage-foundations": {
        "summary": "Introduce non-medical wellness massage concepts with consent, professional boundaries, positioning, draping, comfort communication, sanitation, basic relaxation-oriented touch concepts, and referral awareness.",
        "scope": "Educational wellness content only. Massage therapy licensing and permitted techniques vary by jurisdiction. This unit does not by itself authorize a learner to perform massage therapy or any medical, rehabilitative, diagnostic, or therapeutic procedure.",
        "estimated_minutes": 150,
        "prerequisites": ["Cosmetology Foundations", "CrownPath professional conduct and sanitation orientation"],
        "materials": ["Practice table or chair appropriate to instructor-approved demonstration", "Clean linens or draping materials", "Hand-hygiene supplies", "Instructor-approved lotion or lubricant if applicable", "Bolsters or positioning supports", "Client preference/consent form", "Sanitation supplies"],
        "objectives": ["Explain the difference between general wellness education and licensed massage therapy.", "Use consent, privacy, boundaries, draping, positioning, and comfort checks appropriately.", "Demonstrate instructor-approved non-medical relaxation concepts only where lawful.", "Maintain clean linens, hands, surfaces, and equipment.", "Recognize situations that require stopping, postponing, or referral."],
        "lesson_sections": [
            {"title": "Scope and professional boundaries", "content": "Before any hands-on activity, determine whether the technique is lawful for the learner's credential and location. CrownPath can teach wellness concepts, communication, positioning, sanitation, and awareness, but completion of this lesson does not create a massage license. Never represent a wellness service as medical treatment, rehabilitation, pain treatment, or disease management unless separately qualified and legally authorized."},
            {"title": "Consent and client control", "content": "Explain the planned service, areas involved, positioning, draping, approximate duration, and the client's right to decline or stop at any time. Obtain consent before beginning and again before changing the planned area or technique. Respect privacy and never assume consent from silence."},
            {"title": "Positioning, draping, and comfort", "content": "Use stable positioning and supports to reduce unnecessary strain. Draping should protect privacy and expose only the area necessary for an authorized technique. Ask about temperature, pressure, positioning, and comfort. Adjust or stop when requested."},
            {"title": "Sanitation and product handling", "content": "Clean hands before and after service, use fresh linens for each client, clean applicable surfaces and equipment, and handle lotions or other products hygienically. Follow manufacturer directions and applicable infection-control requirements."},
            {"title": "Relaxation-oriented touch concepts", "content": "Where lawful and instructor-approved, learners may study broad concepts such as controlled contact, smooth transitions, light relaxation-oriented strokes, rhythm, pacing, and client feedback. CrownPath does not use this unit to authorize deep tissue work, injury treatment, manipulation, medical massage, or other regulated techniques outside the learner's scope."},
            {"title": "Stop and referral decisions", "content": "Do not proceed when the client reports a concern that requires medical evaluation, when there is visible open injury or another unsafe condition, when the learner lacks required credentials, or when consent is uncertain. Concerning symptoms require appropriate qualified or emergency care rather than an improvised wellness intervention."}
        ],
        "steps": ["Confirm the service purpose, client preferences, boundaries, and relevant safety information.", "Prepare a clean, private environment and position the client comfortably with appropriate draping.", "Use only techniques permitted by the practitioner's training, credential, and jurisdiction while continually checking comfort.", "End gradually, provide general non-medical aftercare guidance, sanitize the area, and document the service when required."],
        "demonstration": {"title": "Wellness service setup and communication demonstration", "instructions": ["Demonstrate consent language and explain the client's right to stop.", "Show clean linen setup, hand hygiene, privacy protection, and safe positioning.", "Demonstrate instructor-approved relaxation concepts only if lawful for the training setting.", "Model pressure and comfort check-ins without making medical claims.", "Demonstrate closeout, linen handling, surface sanitation, and documentation." ]},
        "guided_practice": ["Learners practice a verbal consent and boundary conversation.", "Learners demonstrate positioning and draping on a mannequin, simulation aid, or consenting model under instructor supervision where lawful.", "Learners identify which example services require a separate massage credential in the applicable jurisdiction.", "Learners practice stop-service and referral language."],
        "knowledge_check": [
            {"question": "Does completing this CrownPath unit automatically authorize a learner to practice massage therapy?", "options": ["Yes, everywhere", "No; licensing and scope requirements vary and must be independently satisfied", "Only if a client agrees", "Only on weekends"], "answer_index": 1, "rationale": "Educational completion does not replace jurisdiction-specific licensing or credential requirements."},
            {"question": "What should happen if a client withdraws consent during a wellness service?", "options": ["Continue until the planned time ends", "Stop the affected activity promptly and respect the client's decision", "Ask a bot to overrule the client", "Ignore the request if pressure is light"], "answer_index": 1, "rationale": "Client consent remains active and revocable throughout the service."},
            {"question": "Which claim is outside this general wellness lesson?", "options": ["This may be a relaxing experience", "Please tell me if the pressure is uncomfortable", "This technique will medically treat your injury", "You may ask me to stop at any time"], "answer_index": 2, "rationale": "Medical treatment claims are outside the unit's non-medical wellness scope."}
        ],
        "practical_checkoff": ["Explains scope and obtains consent", "Protects privacy", "Uses appropriate positioning and draping", "Maintains sanitation", "Checks comfort", "Stays within authorized technique boundaries", "Recognizes stop/referral scenarios", "Completes safe closeout"],
        "avatar_bot": {"role": "Wellness Massage Learning Guide", "allowed": ["Teach consent and boundary concepts", "Guide sanitation and setup checklists", "Prompt comfort communication", "Explain that licensing varies by jurisdiction"], "prohibited": ["Diagnose injuries or conditions", "Prescribe treatment", "Authorize massage practice without required credentials", "Generate medical rehabilitation plans", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath Wellness Massage Safety Flow", "sections": ["VERIFY SCOPE before hands-on activity.", "CONSENT: explain service, areas, draping and right to stop.", "PREPARE: clean hands, linens, surfaces, products and supports.", "COMFORT: positioning, temperature, pressure and privacy checks.", "BOUNDARIES: use only techniques lawful for your credential and training.", "STOP/REFER when consent changes, safety is uncertain, credentials are insufficient, or concerns fall outside wellness scope."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "Massage licensing and scope vary by jurisdiction. CrownPath education does not authorize massage therapy where a separate license or credential is required."
    },
    "wellness-fitness-foundations": {
        "summary": "Teach general fitness and wellness foundations including movement preparation, mobility, basic strength concepts, gradual progression, recovery, hydration, sleep, body awareness, and stop-exercise warning signs.",
        "scope": "General educational wellness information only. This unit is not individualized medical care, physical therapy, rehabilitation, nutrition therapy, or a personalized exercise prescription.",
        "estimated_minutes": 120,
        "prerequisites": ["CrownPath wellness orientation"],
        "materials": ["Clear movement area", "Supportive chair or stable surface", "Light instructor-approved resistance equipment if used", "Water access", "Movement observation checklist", "Emergency contact/procedure information for the training setting"],
        "objectives": ["Explain warm-up, mobility, strength, balance, recovery, hydration, and sleep as general wellness concepts.", "Use gradual progression instead of sudden overload.", "Demonstrate basic body-awareness and controlled movement principles.", "Recognize warning signs that require stopping activity.", "Distinguish general wellness education from individualized clinical or exercise prescription."],
        "lesson_sections": [
            {"title": "Movement preparation", "content": "A warm-up gradually prepares the body for activity. General examples can include easy walking, controlled joint movement, and rehearsal of the movement pattern at low effort. The goal is preparation, not exhaustion."},
            {"title": "Mobility, balance, and movement quality", "content": "Mobility involves usable movement through a comfortable range. Balance and coordination improve through controlled practice suited to the learner's ability. Avoid forcing painful ranges. Use stable support when needed and keep the training area free of hazards."},
            {"title": "Basic strength concepts", "content": "Strength improves when muscles are challenged progressively and given recovery. General education may introduce bodyweight or light-resistance patterns, controlled tempo, posture, and technique. CrownPath should not generate individualized loads or rehabilitation prescriptions for a medical condition without an appropriately qualified professional."},
            {"title": "Gradual progression", "content": "Increase challenge gradually by changing one factor at a time, such as repetitions, resistance, duration, or complexity. Sudden large increases can raise the chance of excessive soreness or injury. Quality of movement and recovery matter more than rushing progression."},
            {"title": "Recovery, hydration, and sleep", "content": "General wellness includes adequate recovery between challenging sessions, access to fluids, regular sleep, and attention to fatigue. Individual fluid, nutrition, medical, or recovery needs can vary substantially and may require qualified guidance."},
            {"title": "Stop-exercise awareness", "content": "Stop activity for concerning symptoms such as chest pain, fainting, severe shortness of breath, sudden severe pain, new neurological symptoms, or another alarming change. Seek appropriate emergency or professional care rather than attempting to exercise through a serious warning sign."},
            {"title": "Professional boundaries", "content": "A CrownPath learner can explain general movement and wellness principles but should not diagnose injuries, prescribe rehabilitation, claim to cure disease, or create medical nutrition plans. Personalized exercise programming may require additional qualifications depending on the setting and client needs."}
        ],
        "steps": ["Begin with an appropriate warm-up and assess comfort before increasing effort.", "Use controlled technique and gradual progression rather than sudden overload.", "Include recovery, hydration, sleep, and general wellness habits as part of the routine.", "Stop activity for concerning symptoms and seek appropriate professional or emergency care when indicated."],
        "demonstration": {"title": "General wellness movement session", "instructions": ["Demonstrate a gradual low-intensity warm-up.", "Show a small set of instructor-approved mobility and balance examples with stable support options.", "Demonstrate a simple bodyweight or light-resistance movement emphasizing controlled technique rather than maximum effort.", "Explain how to progress gradually and how recovery fits into the plan.", "Model an immediate stop response to a hypothetical warning-sign scenario." ]},
        "guided_practice": ["Learners lead a short general warm-up using instructor-approved movements.", "Learners identify safe ways to simplify or reduce intensity without diagnosing a participant.", "Learners build a sample general wellness sequence using warm-up, controlled activity, and recovery.", "Learners sort scenario cards into continue, reduce/modify, stop, and seek appropriate care."],
        "knowledge_check": [
            {"question": "What is the main purpose of a warm-up?", "options": ["Reach exhaustion before exercise", "Gradually prepare for activity", "Diagnose an injury", "Replace recovery"], "answer_index": 1, "rationale": "A warm-up prepares the body gradually rather than exhausting it."},
            {"question": "Which progression approach best fits this course?", "options": ["Increase everything at once", "Use gradual changes while monitoring technique and recovery", "Ignore pain", "Always train at maximum effort"], "answer_index": 1, "rationale": "Gradual progression supports safer learning and adaptation."},
            {"question": "What should a participant do for chest pain or fainting during activity?", "options": ["Push through it", "Stop activity and seek appropriate emergency or professional care", "Ask an avatar for a diagnosis", "Add more resistance"], "answer_index": 1, "rationale": "Serious warning signs require stopping and appropriate care."}
        ],
        "practical_checkoff": ["Prepares a clear safe movement area", "Leads a gradual warm-up", "Demonstrates controlled movement", "Uses reasonable support/modification options", "Explains gradual progression", "Includes recovery concepts", "Recognizes serious stop-exercise warning signs", "Stays within general wellness scope"],
        "avatar_bot": {"role": "Fitness Foundations Coach", "allowed": ["Teach general warm-up and recovery concepts", "Prompt technique checklists", "Explain gradual progression", "Remind learners of stop-exercise warning signs"], "prohibited": ["Diagnose injury or disease", "Prescribe rehabilitation", "Create medical nutrition plans", "Override emergency guidance", "Reveal instructor answer keys"]},
        "student_handout": {"title": "CrownPath General Fitness Flow", "sections": ["PREPARE: clear area, supportive setup, easy warm-up.", "MOVE: controlled range, balance, posture and technique.", "PROGRESS: change challenge gradually, not all at once.", "RECOVER: rest, fluids, sleep and attention to fatigue.", "STOP: chest pain, fainting, severe shortness of breath, sudden severe pain, neurological symptoms or other alarming changes require appropriate care.", "SCOPE: general wellness education is not medical diagnosis, rehabilitation or individualized clinical prescription."]},
        "printable": {"enabled": True, "exclude_answer_key_for_learners": True},
        "safety_note": "This is general wellness education, not individualized medical, rehabilitation, nutrition, or exercise-prescription advice."
    },
}


def get_wellness_lesson_content(lesson_id: str):
    return WELLNESS_LESSON_CONTENT.get(lesson_id)
